# import pandas as pd

# product_name = pd.read_csv('validation.csv')
# label_df = pd.read_csv('validation_data.csv')

# label = []
# product = []
# for index, row in label_df.iterrows():
#     value = row['Label']
#     for index2, row2 in product_name.iterrows():
#         value2 = row2['Product Name']
#         if value in value2:
#             label.append(value)
#             product.append(value2)

# result = pd.DataFrame({'Label': label, 'Product Name': product})
# result.to_csv('temp.csv', index=False)

# import pandas as pd
# import warnings
# warnings.filterwarnings("ignore", 'This pattern is interpreted as a regular expression, and has match groups')
# validation = pd.read_csv('validation_data.csv')
# df = pd.read_csv('df2.csv')

# result_dict = []
# for index, row in validation.iterrows():
#     value = row['Label']
#     result_dict.append(value)

# for value in result_dict:
#     df.loc[df['Product Name'].str.contains(value), 'Label'] = value

# df.to_csv('df3.csv', index=False)
# print("Done")

import pandas as pd
import warnings
warnings.filterwarnings("ignore", 'This pattern is interpreted as a regular expression, and has match groups')
# Read the dataframe from a file or create it
df = pd.read_csv('predicted_labels2.csv')
lastpart = pd.read_csv('lastpart.csv')
df2 = pd.read_csv('df2.csv')

substring_replacements = {
    'Ghế văn phòng': 'Ghế văn phòng',
'Thước dây': 'Thước dây',
'Thước cuộn': 'Thước dây',
'Cưa tay': 'Cưa tay',
'Váy, đầm': 'Váy, đầm',
'Dụng cụ đo, kiểm tra khác': 'Dụng cụ đo, kiểm tra khác',
'Linh kiện máy photocopy': 'Linh kiện máy photocopy',
'Bàn ghế trang điểm': 'Bàn ghế trang điểm',
'Mobile': 'Mobile',
'Sản phẩm dành cho da nám, tàn nhang': 'Sản phẩm dành cho da nám, tàn nhang',
'Sạc pin ngoài cho điện thoại': 'Sạc pin ngoài cho điện thoại',
'Nước hoa hồng': 'Nước hoa hồng',
'Váy xòe': 'Váy xòe',
'Hệ thống camera giám sát': 'Hệ thống camera giám sát',
'Chuột máy tính': 'Chuột máy tính ( Mouse)',
'Khung treo tivi': 'Khung treo tivi',
'Cốc, chén ...': 'Cốc, chén ...',
'Tủ thờ Thần Tài': 'Tủ thờ Thần Tài',
'Bao đựng, ốp lưng điện thoại': 'Bao đựng, ốp lưng điện thoại',
'Giá, kệ để hàng': 'Giá, kệ để hàng',
'Đồ độ xe máy': 'Đồ độ xe máy',
'Rổ, rá các loại': 'Rổ, rá các loại',
'Áo khoác cách điệu': 'Áo khoác cách điệu',
'Quần lót nữ': 'Quần lót nữ',
'Đồ bảo vệ sức khoẻ': 'Đồ bảo vệ sức khoẻ',
'Giường': 'Giường',
'Giày da nam': 'Giày da nam',
'Áo trẻ em': 'Áo trẻ em',
'Máy li tâm': 'Máy li tâm',
'Bộ bàn ghế ( phòng ăn, bếp )': 'Bộ bàn ghế ( phòng ăn, bếp )',
'Vải': 'Vải',
'Tranh gạch': 'Tranh gạch',
'Loa ngoài cho laptop, máy nghe nhạc': 'Loa ngoài cho laptop, máy nghe nhạc',
'Máy sấy công nghiệp': 'Máy sấy công nghiệp',
'Sản phẩm dùng cho da vùng mắt': 'Sản phẩm dùng cho da vùng mắt',
'Đồng hồ hàng hiệu nam': 'Đồng hồ hàng hiệu nam',
'Áo hai dây, áo quây': 'Áo hai dây, áo quây',
'Máy phát điện công nghiệp': 'Máy phát điện công nghiệp',
'Đồ chơi bằng gỗ': 'Đồ chơi bằng gỗ',
'Đạo cụ ảo thuật': 'Đạo cụ ảo thuật',
'Bật lửa, hộp quẹt': 'Bật lửa, hộp quẹt',
'Sơn': 'Sơn',
'Thiết bị ngành tóc': 'Thiết bị ngành tóc',
'Camera IP': 'Camera IP',
'Áo sơ mi nữ': 'Áo sơ mi nữ',
'Bộ chăn ga gối đệm': 'Bộ chăn ga gối đệm',
'Thiết bị tự động hóa': 'Thiết bị tự động hóa',
'Kem đánh răng': 'Kem đánh răng',
'Tủ, giá để thiết bị': 'Tủ, giá để thiết bị',
'Hot Deal Ẩm thực': 'Hot Deal Ẩm thực',
'Ví, bóp nam': 'Ví, bóp nam',
'Đồng phục học sinh- sinh viên': 'Đồng phục học sinh- sinh viên',
'Thiết bị trình chiếu': 'Thiết bị trình chiếu',
'Tranh nghệ thuật': 'Tranh nghệ thuật',
'Máy nghe nhạc Mp4': 'Máy nghe nhạc Mp4',
'Sập': 'Sập',
'Phụ kiện xăm': 'Phụ kiện xăm',
'Tivi Box': 'Tivi Box',
'Đồ thủ công mỹ nghệ khác': 'Đồ thủ công mỹ nghệ khác',
'Thanh lăn khử mùi': 'Thanh lăn khử mùi',
'Quần kaki nam': 'Quần kaki nam',
'Máy hút mùi': 'Máy hút mùi',
'Máy chấm công': 'Máy chấm công',
'Đá mài': 'Đá mài',
'Lều, bạt': 'Lều, bạt',
'Kìm': 'Kìm',
'Gương chiếu hậu xe đạp': 'Gương chiếu hậu xe đạp',
'Bông tai, hoa tai nữ': 'Bông tai, hoa tai nữ',
'Máy tính phòng Net - Game': 'Máy tính phòng Net - Game',
'Áo bò nữ': 'Áo bò nữ',
'Cao dán': 'Cao dán',
'Áo thun nam (áo phông)': 'Áo thun nam (áo phông)',
'Bát, đĩa ...': 'Bát, đĩa ...',
'Máy lọc nước': 'Máy lọc nước',
'Đồ lót nam': 'Đồ lót nam',
'Bánh trung thu': 'Bánh trung thu',
'Đèn pin, đèn xách': 'Đèn pin, đèn xách',
'Máy đo độ pH': 'Máy đo độ pH',
'Bàn vi tính': 'Bàn vi tính',
'Đồ chơi mô hình khác': 'Đồ chơi mô hình khác',
'Giày thể thao nam': 'Giày thể thao nam',
'Lốp xe ôtô': 'Lốp xe ôtô',
'Kem tẩy da chết toàn thân': 'Kem tẩy da chết toàn thân',
'Bóng đèn': 'Bóng đèn',
'Tuốc nơ vít ( tô vít )': 'Tuốc nơ vít ( tô vít )',
'Tượng thờ': 'Tượng thờ',
'Dép, Sandal nam': 'Dép, Sandal nam',
'Đồng phục sự kiện': 'Đồng phục sự kiện',
'Đồng hồ trang trí': 'Đồng hồ trang trí',
'Ghế cafe ( café)': 'Ghế cafe ( café)',
'Túi, cặp xách tổng hợp nữ': 'Túi, cặp xách tổng hợp nữ',
'Mặt nạ, hấp, ủ dưỡng tóc': 'Mặt nạ, hấp, ủ dưỡng tóc',
'Đèn xe máy': 'Đèn xe máy',
'Áo da nam': 'Áo da nam',
'Chăm sóc mẹ khi sinh': 'Chăm sóc mẹ khi sinh',
'Giấy': 'Giấy',
'Ghế Sun Lounger': 'Ghế Sun Lounger',
'Bê tông': 'Bê tông, vữa',
'Bộ chuyển đổi - Converter': 'Bộ chuyển đổi - Converter',
'Sofa, salon': 'Sofa, salon',
'Bàn làm việc văn phòng': 'Bàn làm việc văn phòng',
'Máy xúc đào': 'Máy xúc đào',
'Thước thủy': 'Thước thuỷ',
'Máy ép mía': 'Máy ép mía',
'Thời trang dạ hội': 'Thời trang dạ hội',
'Phụ kiện lọc nước tinh khiết': 'Phụ kiện lọc nước tinh khiết',
'Áo sơ mi nam': 'Áo sơ mi nam',
'Tinh dầu chăm sóc tóc': 'Tinh dầu chăm sóc tóc',
'Bàn ghế phòng khách': 'Bàn ghế phòng khách',
'Dây lưng (thắt lưng) nam': 'Dây lưng (thắt lưng) nam',
'Tủ kệ phòng khách': 'Tủ kệ phòng khách',
'Máy in hóa đơn': 'Máy in hóa đơn',
'Bàn chải đánh răng': 'Bàn chải đánh răng',
'Dầu xả': 'Dầu xả',
'Trải sàn - Lót sàn': 'Trải sàn - Lót sàn',
'Đồng hồ cây': 'Đồng hồ cây',
'Đàn Piano': 'Đàn Piano',
'Bình thủy, Phích điện': 'Bình thủy, Phích điện',
'Găng tay bảo hộ': 'Găng tay bảo hộ',
'Mũ, nón nam': 'Mũ, nón nam',
'Tủ rượu': 'Tủ rượu',
'Đồng phục nhà hàng- Khách sạn': 'Đồng phục nhà hàng- Khách sạn',
'Bộ chìa lục giác ( lục lăng )': 'Bộ chìa lục giác ( lục lăng )',
'Nước hoa ôtô': 'Nước hoa ôtô',
'Phụ kiện bảng tương tác': 'Phụ kiện bảng tương tác',
'Hub - Switch': 'Hub - Switch',
'Máy chưng cất rượu': 'Máy chưng cất rượu',
'Cân nhà bếp': 'Cân nhà bếp',
'Bộ bàn ghế cafe': 'Bộ bàn ghế cafe',
'Áo dài nữ': 'Áo dài nữ',
'Phụ kiện teen nữ': 'Phụ kiện teen nữ',
'Ống nước': 'Ống nước',
'MacBook': 'MacBook',
'Màn ngăn PVC': 'Màn ngăn PVC',
'Dây đồng hồ': 'Dây đồng hồ',
'Dụng cụ ăn uống vật nuôi': 'Dụng cụ ăn uống vật nuôi',
'Mặt nạ': 'Mặt nạ',
'Chậu rửa Lavabo để bàn': 'Chậu rửa Lavabo để bàn',
'Áo khoác trẻ em': 'Áo khoác trẻ em',
'Bàn ghế học tập và giảng dạy': 'Bàn ghế học tập và giảng dạy',
'Áo thể thao nữ': 'Áo thể thao nữ',
'Giàn phơi': 'Giàn phơi',
'Thực phẩm bổ dưỡng từ thiên nhiên': 'Thực phẩm bổ dưỡng từ thiên nhiên',
'Vỏ nhựa xe máy': 'Vỏ nhựa xe máy',
'Máy nén khí trục vít': 'Máy nén khí trục vít',
'Bàn ghế sân vườn': 'Bàn ghế sân vườn',
'Dây thắt thời trang nữ': 'Dây thắt thời trang nữ',
'Máy tính Desktop': 'Máy tính Desktop',
'Đồ chơi thử thách trí tuệ': 'Đồ chơi thử thách trí tuệ',
'Sập thờ': 'Sập thờ',
'Nhẫn nữ': 'Nhẫn nữ',
'Quần áo bảo hộ': 'Quần áo bảo hộ',
'Phụ kiện ống dẫn công nghiệp': 'Phụ kiện ống dẫn công nghiệp',
'Lọc dầu Ô tô': 'Lọc dầu Ô tô',
'Tổ yến qua sơ chế': 'Tổ yến qua sơ chế',
'Pallet': 'Pallet',
'Áo lót nữ': 'Áo lót nữ',
'Cửa gỗ': 'Cửa gỗ',
'Kích thuỷ lực ( Con đội thủy lực )': 'Kích thuỷ lực ( Con đội thủy lực )',
'Áo len nữ': 'Áo len nữ',
'Bình chữa cháy': 'Bình chữa cháy',
'Bình, Lọ hoa': 'Bình, Lọ hoa',
'Gạch ốp lát': 'Gạch ốp lát',
'Van điện từ': 'Van điện từ',
'Kính áp tròng': 'Kính áp tròng',
'Áo thun nữ (áo pull)': 'Áo thun nữ (áo pull)',
'Phụ kiện tủ điện': 'Phụ kiện tủ điện',
'Đồng hồ thông minh (SmartWatch)': 'Đồng hồ thông minh (SmartWatch)',
'Áo thun đôi': 'Áo thun đôi',
'Bộ đồ nấu bếp': 'Bộ đồ nấu bếp',
'Kẹo cao su': 'Kẹo cao su',
'Đèn Led': 'Đèn Led',
'Két sắt, két bạc': 'Két sắt, két bạc',
'Chậu rửa bát có hộp Inox': 'Chậu rửa bát có hộp Inox',
'Server (Máy chủ)': 'Server (Máy chủ)',
'Đồ chơi dùng pin': 'Đồ chơi dùng pin',
'Robot lắp ráp': 'Robot lắp ráp',
'Downlight': 'Downlight',
'Van cửa ( van cổng )': 'Van cửa ( van cổng )',
'Đèn tranh': 'Đèn tranh',
'Sản phẩm chống nắng toàn thân': 'Sản phẩm chống nắng toàn thân',
'Đèn bàn': 'Đèn bàn',
'Đèn thả': 'Đèn thả',
'Máy tính laptop': 'Máy tính laptop',
'Nước hoa nữ': 'Nước hoa nữ',
'Tương ớt': 'Tương ớt',
'Bàn phím laptop': 'Bàn phím laptop',
'Đồ chơi nhạc cụ': 'Đồ chơi nhạc cụ',
'Xe nâng tay': 'Xe nâng tay',
'Máy hút chân không': 'Máy hút chân không',
'Thiết bị rửa xe Ôtô': 'Thiết bị rửa xe Ôtô',
'Ghế giám đốc': 'Ghế giám đốc',
'Đồ phong thủy': 'Đồ phong thủy',
'Loa nghe nhạc': 'Loa nghe nhạc',
'Chậu rửa bát không bàn lắp âm bàn': 'Chậu rửa bát không bàn lắp âm bàn',
'Phụ kiện ống nước': 'Phụ kiện ống nước',
'Lốp xe nâng': 'Lốp xe nâng',
'Phù điêu, tượng': 'Phù điêu, tượng',
'Thiết bị phòng chống sét': 'Thiết bị phòng chống sét',
'Túi đựng máy ảnh': 'Túi đựng máy ảnh',
'Vòi rửa, vòi nước': 'Vòi rửa, vòi nước',
'Linh kiện điện tử': 'Linh kiện điện tử',
'Dung dịch rửa tay': 'Dung dịch rửa tay',
'Đồng phục bệnh viện': 'Đồng phục bệnh viện',
'Giỏ, khay, kệ': 'Giỏ, khay, kệ',
'Bảo vệ, chống nóng cho ô tô': 'Bảo vệ, chống nóng cho ô tô',
'Ghép hình nhà cửa': 'Ghép hình nhà cửa',
'Camera giám sát': 'Camera giám sát',
'Lõi lọc nước': 'Lõi lọc nước',
'Dầu gội đầu': 'Dầu gội đầu',
'Bơ, pho mát (cheese)': 'Bơ, pho mát (cheese)',
'Balo thời trang': 'Balo thời trang',
'Tủ quần áo': 'Tủ quần áo',
'Váy bầu': 'Váy bầu',
'Sản phẩm dưỡng da mặt': 'Sản phẩm dưỡng da mặt',
'Quầy bar nhà hàng': 'Quầy bar nhà hàng',
'Kẹo hoa quả': 'Kẹo hoa quả',
'Thức ăn vật nuôi': 'Thức ăn vật nuôi',
'Hoành phi, câu đối': 'Hoành phi, câu đối',
'Microphone': 'Microphone',
'Ống kính cho điện thoại': 'Ống kính cho điện thoại',
'Chống ồn Ô tô': 'Chống ồn Ô tô',
'Thùng đựng đồ nghề': 'Thùng đựng đồ nghề',
'Gỗ mỹ nghệ': 'Gỗ mỹ nghệ',
'Giày, dép khác': 'Giày, dép khác',
'Sản phẩm tẩy da chết cho da mặt': 'Sản phẩm tẩy da chết cho da mặt',
'Bàn cafe ( café)': 'Bàn cafe ( café)',
'Bộ mỹ phẩm tổng hợp': 'Bộ mỹ phẩm tổng hợp',
'Thiết bị kiểm soát ra vào': 'Thiết bị kiểm soát ra vào',
'Máy hàn Mig/Mag': 'Máy hàn Mig/Mag',
'Hóa chất tinh khiết': 'Hóa chất tinh khiết',
'Khay đựng thức ăn, đồ uống': 'Khay đựng thức ăn, đồ uống',
'Van bướm': 'Van bướm',
'Các loại phụ kiện ô tô khác': 'Các loại phụ kiện ô tô khác',
'Tủ tài liệu': 'Tủ tài liệu',
'Đào tạo lái xe ô tô': 'Đào tạo lái xe ô tô',
'Xe máy': 'Xe máy',
'Đèn áp trần': 'Đèn áp trần',
'Boot nữ': 'Boot nữ',
'Tinh dầu (Chăm sóc cơ thể)': 'Tinh dầu (Chăm sóc cơ thể)',
'Phụ kiện thiết bị nâng hạ': 'Phụ kiện thiết bị nâng hạ',
'Màn hình Mobile, PDA phone': 'Màn hình Mobile, PDA phone',
'Phụ kiện cho đồng hồ thông minh': 'Phụ kiện cho đồng hồ thông minh',
'Máy trộn bột': 'Máy trộn bột',
'Chiết áp': 'Chiết áp',
'Tủ nhựa': 'Tủ nhựa',
'Thẻ nhớ': 'Thẻ nhớ',
'Mascara': 'Mascara',
'Chân máy ảnh (Tripod)': 'Chân máy ảnh (Tripod)',
'Xe chuyên dụng': 'Xe chuyên dụng',
'Mực in': 'Mực in',
'Sen vòi': 'Sen vòi',
'Đồ chơi tổng hợp khác': 'Đồ chơi tổng hợp khác',
'Tấm ốp tường': 'Tấm ốp tường',
'Cháo ăn liền': 'Cháo ăn liền',
'Thực phẩm tăng cường sức khỏe': 'Thực phẩm tăng cường sức khỏe',
'Phụ kiện giàn giáo, cốp pha': 'Phụ kiện giàn giáo, cốp pha',
'Ống đựng nhang (hương)': 'Ống đựng nhang (hương)',
'Các phụ tùng xe máy khác': 'Các phụ tùng xe máy khác',
'Phụ kiện làm bánh': 'Phụ kiện làm bánh',
'Son': 'Son',
'Đồ dùng đựng thực phẩm': 'Đồ dùng đựng thực phẩm',
'Thiết bị đo nhiệt độ': 'Thiết bị đo nhiệt độ',
'Phụ kiện thiết bị âm thanh': 'Phụ kiện thiết bị âm thanh',
'Bàn mổ, giường khám': 'Bàn mổ, giường khám',
'Đồ chơi nhân vật': 'Đồ chơi nhân vật',
'Body liền cho bé': 'Body liền cho bé',
'Tinh bột nghệ': 'Tinh bột nghệ',
'Đồ chơi lắp ghép': 'Đồ chơi lắp ghép',
'Mắt kính thời trang': 'Mắt kính thời trang',
'Mỹ phẩm cao cấp - Trang điểm': 'Mỹ phẩm cao cấp - Trang điểm',
'Bồn tắm đứng (vách kính)': 'Bồn tắm đứng (vách kính)',
'Phục trang nữ khác': 'Phục trang nữ khác',
'Bọc tay lái': 'Bọc tay lái',
'Gối': 'Gối',
'Máy xông hơi ướt': 'Máy xông hơi ướt',
'Tủ trẻ em': 'Tủ trẻ em',
'Bàn ghế trẻ em': 'Bàn ghế trẻ em',
'Đồng hồ đeo tay Trung Quốc nữ': 'Đồng hồ đeo tay Trung Quốc nữ',
'Các sản phẩm nhựa khác': 'Các sản phẩm nhựa khác',
'Giường trẻ em': 'Giường trẻ em',
'Cửa nhựa': 'Cửa nhựa',
'Váy suông': 'Váy suông',
'Quạt thông gió công nghiệp': 'Quạt thông gió công nghiệp',
'Cảm biến lực': 'Cảm biến lực',
'Bàn ghế nhựa': 'Bàn ghế nhựa',
'Bột màu công nghiệp': 'Bột màu công nghiệp',
'Nồi xào nấu công nghiệp': 'Nồi xào nấu công nghiệp',
'Sữa tắm': 'Sữa tắm',
'Thép ống': 'Thép ống',
'Đồng phục công nhân': 'Đồng phục công nhân',
'Cà phê phin': 'Cà phê phin',
'Sản phẩm chăm sóc bàn chân': 'Sản phẩm chăm sóc bàn chân',
'Đĩa chà nhám': 'Đĩa chà nhám',
'Cửa chống cháy': 'Cửa chống cháy',
'Vách tắm ( Cabin tắm )': 'Vách tắm ( Cabin tắm )',
'Bàn thờ treo': 'Bàn thờ treo',
'Xe tải': 'Xe tải',
'Bộ tản nhiệt CPU laptop': 'Bộ tản nhiệt CPU laptop',
'Dao đa năng': 'Dao đa năng',
'Ghế hội trường, rạp hát': 'Ghế hội trường, rạp hát',
'Sàn gỗ': 'Sàn gỗ',
'Bộ giũa': 'Bộ giũa',
'Máy cưa đĩa': 'Máy cưa đĩa',
'Cờ lê': 'Cờ lê',
'Máy xay thực phẩm': 'Máy xay thực phẩm',
'Máy xay sinh tố': 'Máy xay sinh tố',
'Mũ, nón đồng phục sự kiện': 'Mũ, nón đồng phục sự kiện',
'Tai nghe bluetooth': 'Tai nghe bluetooth',
'Án gian thờ': 'Án gian thờ',
'Quà tặng gốm sứ': 'Quà tặng gốm sứ',
'Cần xiết lực': 'Cần xiết lực',
'Phụ kiện nhà bếp công nghiệp': 'Phụ kiện nhà bếp công nghiệp',
'Hạt nêm': 'Hạt nêm',
'Xe đẩy thiết bị y tế': 'Xe đẩy thiết bị y tế',
'Khóa': 'Khóa',
'Vật liệu đóng gói hàng hóa': 'Vật liệu đóng gói hàng hóa',
'Kệ tivi': 'Kệ tivi',
'Ghép hình xe cộ': 'Ghép hình xe cộ',
'Đồng phục công sở': 'Đồng phục công sở',
'Băng vệ sinh': 'Băng vệ sinh',
'Đèn chụp ngoài trời': 'Đèn chụp ngoài trời',
'Xi lanh ( dùng cho máy nén khí )': 'Xi lanh ( dùng cho máy nén khí )',
'Workstation - Máy trạm': 'Workstation - Máy trạm',
'Bộ lưu điện (UPS)': 'Bộ lưu điện (UPS)',
'Xe dành cho người khuyết tật': 'Xe dành cho người khuyết tật',
'Máy đầm đất, bê tông': 'Máy đầm đất, bê tông',
'Ô tô Điện': 'Ô tô Điện',
'Tay co, đẩy thủy lực': 'Tay co, đẩy thủy lực',
'Thước Pan-me': 'Thước Pan-me',
'Vòng bi Ôtô': 'Vòng bi Ôtô',
'Nguồn': 'Nguồn',
'Đồ dùng nhà bếp khác': 'Đồ dùng nhà bếp khác',
'Lưỡi cưa, lưỡi cắt': 'Lưỡi cưa, lưỡi cắt',
'Đồng phục mẫu giáo': 'Đồng phục mẫu giáo',
'Thước thẳng': 'Thước thẳng',
'Thời trang nữ khác': 'Thời trang nữ khác',
'Thiết bị phục hồi chức năng': 'Thiết bị phục hồi chức năng',
'Khẩu trang bảo hộ': 'Khẩu trang bảo hộ',
'Giày cầu lông': 'Giày cầu lông',
'Head Phone - Tai nghe': 'Head Phone - Tai nghe',
'Lắc tay nam': 'Lắc tay nam',
'Bao cao su': 'Bao cao su',
'Van nước': 'Van nước',
'Bộ trống điện tử': 'Bộ trống điện tử',
'Sản phẩm diệt côn trùng': 'Sản phẩm diệt côn trùng',
'Quạt điện công nghiệp': 'Quạt điện công nghiệp',
'Kính lọc (Filter)': 'Kính lọc (Filter)',
'Quần bò nữ (Jeans)': 'Quần bò nữ (Jeans)',
'Thuốc đông y': 'Thuốc đông y',
'Thảm chơi trẻ em': 'Thảm chơi trẻ em',
'Máy chà sàn': 'Máy chà sàn',
'Các loại móc': 'Các loại móc',
'Bàn ghế nhà hàng, khách sạn': 'Bàn ghế nhà hàng, khách sạn',
'Sản phẩm dành cho da lão hóa': 'Sản phẩm dành cho da lão hóa',
'Bàn là': 'Bàn là',
'Giống cây trồng': 'Giống cây trồng',
'Kính mắt hàng hiệu nữ': 'Kính mắt hàng hiệu nữ',
'Sơn móng': 'Sơn móng',
'Đồ dùng trong nhà tắm': 'Đồ dùng trong nhà tắm',
'Áo khoác nam': 'Áo khoác nam',
'Modem quang': 'Modem quang',
'Giày thể thao trẻ em': 'Giày thể thao trẻ em',
'Thiết bị đo, kiểm tra khí': 'Thiết bị đo, kiểm tra khí',
'Bàn phím': 'Bàn phím',
'Cầu dao tự động ( Aptomat )': 'Cầu dao tự động ( Aptomat )',
'Chân váy': 'Chân váy',
'Contactor ( công tắc tơ )': 'Contactor ( công tắc tơ )',
'Thảm': 'Thảm',
'Thi công xây dựng': 'Thi công xây dựng',
'Sản phẩm tẩy trang mặt': 'Sản phẩm tẩy trang mặt',
'Quạt không cánh': 'Quạt không cánh',
'Chuồng trại chăn nuôi': 'Chuồng trại chăn nuôi',
'Bàn giám đốc': 'Bàn giám đốc',
'Dép, Sandal nữ': 'Dép, Sandal nữ',
'Nước hoa nam': 'Nước hoa nam',
'Ghế phòng chờ': 'Ghế phòng chờ',
'Lót ly, treo ly, gạt tàn ...': 'Lót ly, treo ly, gạt tàn ...',
'Đồ thủy tinh': 'Đồ thủy tinh',
'Sách': 'Sách',
'Hạc thờ': 'Hạc thờ',
'Phục trang trẻ em khác': 'Phục trang trẻ em khác',
'Vật tư phòng thí nghiệm': 'Vật tư phòng thí nghiệm',
'Hóa chất công nghiệp': 'Hóa chất công nghiệp',
'Bình trà, bộ ấm chén': 'Bình trà, bộ ấm chén',
'Bút': 'Bút',
'CPU laptop': 'CPU laptop',
'Thiết bị điều khiển tự động': 'Thiết bị điều khiển tự động',
'Quần nữ khác': 'Quần nữ khác',
'Dao, kéo, dụng cụ cắt gọt ...': 'Dao, kéo, dụng cụ cắt gọt ...',
'Chậu rửa Lavabo âm bàn': 'Chậu rửa Lavabo âm bàn',
'Giày vải nam': 'Giày vải nam',
'Quần thể thao nữ': 'Quần thể thao nữ',
'Logo, Decal Xe máy': 'Logo, Decal Xe máy',
'Đồ ngủ nữ': 'Đồ ngủ nữ',
'Quạt hướng trục': 'Quạt hướng trục',
'Bếp từ': 'Bếp từ',
'Hộp box điện': 'Hộp box điện',
'Máy cạo râu': 'Máy cạo râu',
'Quần áo cả bộ cho trẻ em': 'Quần áo cả bộ cho trẻ em',
'Ống dẫn khí': 'Ống dẫn khí',
'Dụng cụ gá cặp': 'Dụng cụ gá cặp',
'Mũi khoan': 'Mũi khoan',
'Máy vặt lông gia cầm': 'Máy vặt lông gia cầm',
'Máy đo độ nhớt': 'Máy đo độ nhớt',
'Xe đẩy phục vụ': 'Xe đẩy phục vụ',
'Túi nilon': 'Túi nilon',
'Phụ kiện thiết bị công nghiệp khác': 'Phụ kiện thiết bị công nghiệp khác',
'Bộ mỹ phẩm chăm sóc da': 'Bộ mỹ phẩm chăm sóc da',
'Áo dài trẻ em': 'Áo dài trẻ em',
'Quạt ly tâm': 'Quạt ly tâm',
'Gaming Mouse - Chuột game thủ': 'Gaming Mouse - Chuột game thủ',
'Máy phun rửa áp lực': 'Máy phun rửa áp lực',
'Dụng cụ trồng cây, làm vườn': 'Dụng cụ trồng cây, làm vườn',
'Đồng hồ đôi': 'Đồng hồ đôi',
'Ổn áp': 'Ổn áp',
'Bộ điều khiển nhiệt độ': 'Bộ điều khiển nhiệt độ',
'Dàn karaoke': 'Dàn karaoke',
'Giá, kệ, tủ văn phòng khác': 'Giá, kệ, tủ văn phòng khác',
'Giày bóng rổ': 'Giày bóng rổ',
'Thiết bị đo độ ồn': 'Thiết bị đo độ ồn',
'Dây đeo máy ảnh, máy quay': 'Dây đeo máy ảnh, máy quay',
'Dây thắt thời trang nam': 'Dây thắt thời trang nam',
'Tủ hồ sơ': 'Tủ hồ sơ',
'Võng, Ghế xếp': 'Võng, Ghế xếp',
'Cua': 'Cua',
'Ôtô (Du lịch)': 'Ôtô (Du lịch)',
'Kính mắt Trung Quốc nam': 'Kính mắt Trung Quốc nam',
'Đồ chơi thông minh, phát triển trí não khác': 'Đồ chơi thông minh, phát triển trí não khác',
'Hộp nối, hộp chia ngả ( cho ống luồn dây điện )': 'Hộp nối, hộp chia ngả ( cho ống luồn dây điện )',
'Nguyên liệu trà sữa': 'Nguyên liệu trà sữa',
'Dụng cụ siết mở ốc, vít': 'Dụng cụ siết mở ốc, vít',
'Phụ kiện nhà bếp': 'Phụ kiện nhà bếp',
'Ống nhựa xoắn': 'Ống nhựa xoắn',
'Đồng hồ đo km xe máy': 'Đồng hồ đo km xe máy',
'Đèn Exit, sự cố': 'Đèn Exit, sự cố',
'Thịt hun khói': 'Thịt hun khói',
'Thùng rác công cộng': 'Thùng rác công cộng',
'Áo khoác đôi': 'Áo khoác đôi',
'Quà tổng hợp': 'Quà tổng hợp',
'Phụ kiện ống luồn dây điện khác': 'Phụ kiện ống luồn dây điện khác',
'Bình sữa và phụ kiện': 'Bình sữa và phụ kiện',
'Quần thể thao nam': 'Quần thể thao nam',
'Chocolate': 'Chocolate',
'Thanh ray': 'Thanh ray',
'Phụ kiện i-Pad (i-Pad Accessories)': 'Phụ kiện i-Pad (i-Pad Accessories)',
'Bạt phủ xe máy': 'Bạt phủ xe máy',
'Khăn nữ': 'Khăn nữ',
'Máy vắt sổ': 'Máy vắt sổ',
'Giường cũi trẻ em': 'Giường cũi trẻ em',
'Thời trang công sở nữ': 'Thời trang công sở nữ',
'Sofa văn phòng': 'Sofa văn phòng',
'Bình tích áp máy bơm': 'Bình tích áp máy bơm',
'Giá, kệ quán cafe': 'Giá, kệ quán cafe',
'Máy vắt khô': 'Máy vắt khô',
'Rào chắn': 'Rào chắn',
'Váy đuôi cá': 'Váy đuôi cá',
'Lưới thép': 'Lưới thép',
'Giày bệt nữ': 'Giày bệt nữ',
'Ampe kìm': 'Ampe kìm',
'Máy cày, xới đất': 'Máy cày, xới đất',
'Công tắc cảm ứng': 'Công tắc cảm ứng',
'Đồng hồ đeo tay Trung Quốc nam': 'Đồng hồ đeo tay Trung Quốc nam',
'Máy nổ ngô': 'Máy nổ ngô',
'Đệm phím': 'Đệm phím',
'Bơm thả chìm': 'Bơm thả chìm',
'Dưỡng môi': 'Dưỡng môi',
'Đèn tường': 'Đèn tường',
'Dụng cụ sửa chữa': 'Dụng cụ sửa chữa',
'Màu mắt': 'Màu mắt',
'Phụ kiện dụng cụ sửa chữa': 'Phụ kiện dụng cụ sửa chữa',
'Ghế thư giãn ( ghế xích đu )': 'Ghế thư giãn ( ghế xích đu )',
'Đồ ăn liền': 'Đồ ăn liền',
'Áo vest nữ': 'Áo vest nữ',
'Bọc ghế - Lót ghế': 'Bọc ghế - Lót ghế',
'Trang phục teen nam': 'Trang phục teen nam',
'Nguyên liệu thực phẩm khác': 'Nguyên liệu thực phẩm khác',
'Sạc điện thoại': 'Sạc điện thoại',
'Kem nền nữ': 'Kem nền nữ',
'Đồng hồ đeo tay Hồng Kông nam': 'Đồng hồ đeo tay Hồng Kông nam',
'Thước lá': 'Thước lá',
'Ô tô điều khiển từ xa': 'Ô tô điều khiển từ xa',
'RAM (Server)': 'RAM (Server)',
'Dụng cụ ngư nghiệp': 'Dụng cụ ngư nghiệp',
'Tấm dán bảo vệ': 'Tấm dán bảo vệ',
'Bệt toilet': 'Bệt toilet',
'Đèn trụ': 'Đèn trụ',
'Dụng cụ cách điện': 'Dụng cụ cách điện',
'Cửa cuốn': 'Cửa cuốn',
'Ổ cắm điện': 'Ổ cắm điện',
'Tủ bếp': 'Tủ bếp',
'Dây công nghiệp': 'Dây công nghiệp',
'Máy xăm': 'Máy xăm',
'Máy khoan cầm tay': 'Máy khoan cầm tay',
'Đồ uống bổ dưỡng, làm đẹp': 'Đồ uống bổ dưỡng, làm đẹp',
'Các đồ dùng bơi lội khác': 'Các đồ dùng bơi lội khác',
'Mặt dây đá phong thủy': 'Mặt dây đá phong thủy',
'Đàn Ghi-ta (guitar)': 'Đàn Ghi-ta (guitar)',
'Tab đầu giường': 'Tab đầu giường',
'Gỗ thông': 'Gỗ thông',
'Hóa chất thí nghiệm': 'Hóa chất thí nghiệm',
'Xi đánh giày': 'Xi đánh giày',
'Hộp, khay nhựa': 'Hộp, khay nhựa',
'Quả bóng đá': 'Quả bóng đá',
'Máy nghiền thức ăn chăn nuôi': 'Máy nghiền thức ăn chăn nuôi',
'Máy trộn bê tông': 'Máy trộn bê tông',
'Mô hình xe ô tô, xe máy': 'Mô hình xe ô tô, xe máy',
'Máy sấy khí nén': 'Máy sấy khí nén',
'Đặc sản miền Bắc': 'Đặc sản miền Bắc',
'Bếp gas': 'Bếp gas',
'Camera hành trình Ôtô': 'Camera hành trình Ôtô',
'Cáp viễn thông': 'Cáp viễn thông',
'Cặp, túi đựng laptop': 'Cặp, túi đựng laptop',
'Nồi, Xoong': 'Nồi, Xoong',
'Thiết bị cảm biến quang điện': 'Thiết bị cảm biến quang điện',
'Tất nữ': 'Tất nữ',
'Quạt điện dân dụng': 'Quạt điện dân dụng',
'Khăn tắm, khăn mặt ...': 'Khăn tắm, khăn mặt ...',
'Chậu rửa (Lavabo) khác': 'Chậu rửa (Lavabo) khác',
'Cầu nâng xe máy': 'Cầu nâng xe máy',
'Thùng đựng rác': 'Thùng đựng rác',
'Gạt mưa Ôtô': 'Gạt mưa Ôtô',
'Phụ kiện tủ bếp': 'Phụ kiện tủ bếp',
'Pin điện thoại': 'Pin điện thoại',
'Xích': 'Xích',
'Lắc tay đá phong thủy': 'Lắc tay đá phong thủy',
'Nồi áp suất điện': 'Nồi áp suất điện',
'Đèn quay phim': 'Đèn quay phim',
'Bếp âu': 'Bếp âu',
'Bộ lọc khí': 'Bộ lọc khí',
'Lò nướng': 'Lò nướng',
'Máy bơm, lọc bể cá': 'Máy bơm, lọc bể cá',
'Bảng': 'Bảng',
'Thiết bị chuyển đổi điện áp': 'Thiết bị chuyển đổi điện áp',
'Bơm Ôtô': 'Bơm Ôtô',
'Vật tư ngành lạnh': 'Vật tư ngành lạnh',
'Hạt khô, khoai chiên, bắp rang, hoa quả sấy': 'Hạt khô, khoai chiên, bắp rang, hoa quả sấy',
'Bột giặt': 'Bột giặt',
'Kính mắt hàng hiệu nam': 'Kính mắt hàng hiệu nam',
'Túi, cặp xách tổng hợp nam': 'Túi, cặp xách tổng hợp nam',
'Dụng cụ thí nghiệm': 'Dụng cụ thí nghiệm',
'Máy phun sương': 'Máy phun sương',
'Mainboard Laptop': 'Mainboard Laptop',
'Sản phẩm dành cho da bị mụn': 'Sản phẩm dành cho da bị mụn',
'Tinh dầu (Chăm sóc da mặt)': 'Tinh dầu (Chăm sóc da mặt)',
'Sản phẩm dùng cho giày, dép khác': 'Sản phẩm dùng cho giày, dép khác',
'Đục gỗ': 'Đục gỗ',
'Máy bơm thoát nước thải': 'Máy bơm thoát nước thải',
'Túi, cặp xách tổng hợp khác': 'Túi, cặp xách tổng hợp khác',
'Hương đốt (nhang)': 'Hương đốt (nhang)',
'Flycam': 'Flycam',
'Váy trẻ em': 'Váy trẻ em',
'Màn hình máy tính LCD': 'Màn hình máy tính LCD',
'Cần câu': 'Cần câu',
'Đèn pha': 'Đèn pha',
'Quạt trần': 'Quạt trần',
'Caravat nam': 'Caravat nam',
'Phụ kiện Golf': 'Phụ kiện Golf',
'Dây nối (Cable)': 'Dây nối (Cable)',
'Cột ngăn': 'Cột ngăn',
'Quà tặng pha lê, thủy tinh': 'Quà tặng pha lê, thủy tinh',
'Dao kỹ thuật': 'Dao kỹ thuật',
'Áo khoác len nữ': 'Áo khoác len nữ',
'Đồng hồ đo áp suất lốp Ô tô': 'Đồng hồ đo áp suất lốp Ô tô',
'Máy đánh giầy': 'Máy đánh giầy',
'Đầu phun nước': 'Đầu phun nước',
'Hóa chất xử lý chất thải': 'Hóa chất xử lý chất thải',
'Máy may công nghiệp': 'Máy may công nghiệp',
'Ống kính máy ảnh': 'Ống kính máy ảnh',
'Bột ngũ cốc': 'Bột ngũ cốc',
'Tranh đá': 'Tranh đá',
'Phấn phủ': 'Phấn phủ',
'Đồ lót nữ khác': 'Đồ lót nữ khác',
'Sữa rửa mặt': 'Sữa rửa mặt',
'Xe đạp': 'Xe đạp',
'Phần mềm quản lý khách hàng': 'Phần mềm quản lý khách hàng',
'Giày (vớ) sơ sinh': 'Giày (vớ) sơ sinh',
'Sản phẩm dưỡng da toàn thân': 'Sản phẩm dưỡng da toàn thân',
'Máy hàn que': 'Máy hàn que',
'Sản phẩm làm sạch': 'Sản phẩm làm sạch',
'Trà': 'Trà',
'Linh kiện máy in': 'Linh kiện máy in',
'Thiết bị nhà xưởng': 'Thiết bị nhà xưởng',
'Bộ trễ Delay bảo vệ tủ lạnh': 'Bộ trễ Delay bảo vệ tủ lạnh',
'Lens Mount': 'Lens Mount',
'Vật dụng trang trí': 'Vật dụng trang trí',
'Giấy dán tường': 'Giấy dán tường',
'Bộ bàn tủ thờ': 'Bộ bàn tủ thờ',
'Thiết bị ổn định hình ảnh cầm tay': 'Thiết bị ổn định hình ảnh cầm tay',
'Loa trang trí': 'Loa trang trí',
'Bộ bàn phím & Chuột': 'Bộ bàn phím & Chuột',
'Thép vằn': 'Thép vằn',
'Dung dịch tẩy rửa': 'Dung dịch tẩy rửa',
'Bộ quần áo nữ': 'Bộ quần áo nữ',
'Đặc sản miền Trung': 'Đặc sản miền Trung',
'Tủ đông': 'Tủ đông',
'Đèn chiếu sáng công cộng': 'Đèn chiếu sáng công cộng',
'Ghép hình nhân vật': 'Ghép hình nhân vật',
'Chân đế bàn ghế': 'Chân đế bàn ghế',
'Mỏ hàn, mỏ thổi': 'Mỏ hàn, mỏ thổi',
'Chạm đồng': 'Chạm đồng',
'Sản phẩm massage': 'Sản phẩm massage',
'Bộ khẩu, tay khẩu': 'Bộ khẩu, tay khẩu',
'Vật liệu chống thấm': 'Vật liệu chống thấm',
'Dây chuyền, vòng cổ nữ': 'Dây chuyền, vòng cổ nữ',
'Thời trang Tennis': 'Thời trang Tennis',
'Bóng chuyền': 'Bóng chuyền',
'Máy đóng gói': 'Máy đóng gói',
'Đồ ăn khác cho bé': 'Đồ ăn khác cho bé',
'Thiết kế nội thất khác': 'Thiết kế nội thất khác',
'Mũ, nón khác': 'Mũ, nón khác',
'Nước ngọt, nước trái cây, đóng lon': 'Nước ngọt, nước trái cây, đóng lon',
'Gọng kính thuốc': 'Gọng kính thuốc',
'Tủ mạng': 'Tủ mạng',
'Áo khoác phao nữ': 'Áo khoác phao nữ',
'Cao áp màn hình laptop': 'Cao áp màn hình laptop',
'Bánh xe đẩy': 'Bánh xe đẩy',
'Giày thể thao nữ': 'Giày thể thao nữ',
'Phấn má': 'Phấn má',
'Chống ẩm, khử mùi, xịt phòng các loại': 'Chống ẩm, khử mùi, xịt phòng các loại',
'Cân định lượng': 'Cân định lượng',
'Amplifier': 'Amplifier',
'Áo dạ nữ': 'Áo dạ nữ',
'Động cơ điện': 'Động cơ điện',
'Cảm biến tiệm cận': 'Cảm biến tiệm cận',
'Túi xách hàng hiệu nam': 'Túi xách hàng hiệu nam',
'Cảm biến đo tốc độ': 'Cảm biến đo tốc độ',
'In trên vật liệu khác': 'In trên vật liệu khác',
'Kính hiển vi': 'Kính hiển vi',
'Búp bê': 'Búp bê',
'Dụng cụ thi công cáp quang': 'Dụng cụ thi công cáp quang',
'Kính mắt bảo hộ': 'Kính mắt bảo hộ',
'Sản phẩm chống nắng cho da mặt': 'Sản phẩm chống nắng cho da mặt',
'Bình (lọ) hoa thờ': 'Bình (lọ) hoa thờ',
'Thiết kế quảng cáo': 'Thiết kế quảng cáo',
'Đồ dùng sinh hoạt khác': 'Đồ dùng sinh hoạt khác',
'Máy mài góc': 'Máy mài góc',
'Gương soi treo tường': 'Gương soi treo tường',
'HDD di động (Ổ cứng cắm ngoài)': 'HDD di động (Ổ cứng cắm ngoài)',
'Mũ (Nón) bảo hiểm xe máy': 'Mũ (Nón) bảo hiểm xe máy',
'Bộ đồ đôi': 'Bộ đồ đôi',
'Máy câu': 'Máy câu',
'LED trang trí, quảng cáo': 'LED trang trí, quảng cáo',
'Tủ lạnh công nghiệp': 'Tủ lạnh công nghiệp',
'Máy tập chạy bộ': 'Máy tập chạy bộ',
'Túi xách hàng hiệu nữ': 'Túi xách hàng hiệu nữ',
'Máy lọc, khử độc tố rượu': 'Máy lọc, khử độc tố rượu',
'Men bia, rượu': 'Men bia, rượu',
'Đệm (Nệm)': 'Đệm (Nệm)',
'Bàn quầy, bàn lễ tân': 'Bàn quầy, bàn lễ tân',
'Túi giữ nhiệt': 'Túi giữ nhiệt',
'Ôtô cũ': 'Ôtô cũ',
'Giấy in ảnh': 'Giấy in ảnh',
'Khay, hộp đựng xà phòng ( xà bông )': 'Khay, hộp đựng xà phòng ( xà bông )',
'Hình xăm thời trang': 'Hình xăm thời trang',
'Ga thoát sàn': 'Ga thoát sàn',
'Ghế cắt tóc': 'Ghế cắt tóc',
'Áo khoác chống nắng': 'Áo khoác chống nắng',
'Phấn nền': 'Phấn nền',
'Băng keo, hồ dán': 'Băng keo, hồ dán',
'Máy cắt vòng': 'Máy cắt vòng',
'Áo mưa, ủng đi mưa': 'Áo mưa, ủng đi mưa',
'Ghép hình khối': 'Ghép hình khối',
'Nút nhấn': 'Nút nhấn',
'Máy lọc không khí': 'Máy lọc không khí',
'Váy chữ A': 'Váy chữ A',
'Vách ngăn bàn làm việc': 'Vách ngăn bàn làm việc',
'Lư hương': 'Lư hương',
'Thước êke': 'Thước êke',
'Máy cưa bàn trượt': 'Máy cưa bàn trượt',
'Đồng hồ đeo tay Hồng Kông nữ': 'Đồng hồ đeo tay Hồng Kông nữ',
'Máy giặt': 'Máy giặt',
'Máy phun sơn': 'Máy phun sơn',
'Khăn giấy ướt': 'Khăn giấy ướt',
'Nước mắm, xì dầu': 'Nước mắm, xì dầu',
'Vật dụng trang trí vườn': 'Vật dụng trang trí vườn',
'Cây cảnh Tết': 'Cây cảnh Tết',
'Tủ nấu cơm công nghiệp': 'Tủ nấu cơm công nghiệp',
'Ống inox công nghiệp': 'Ống inox công nghiệp',
'Máy in': 'Máy in',
'Bếp nướng thịt Doner': 'Bếp nướng thịt Doner',
'Quần shorts nam': 'Quần shorts nam',
'Thiết bị đo lực căng': 'Thiết bị đo lực căng',
'Gờ giảm tốc': 'Gờ giảm tốc',
'Đàn Piano điện (Digital Pianos)': 'Đàn Piano điện (Digital Pianos)',
'Giầy, ủng bảo hộ': 'Giầy, ủng bảo hộ',
'Vật liệu chống cháy': 'Vật liệu chống cháy',
'Máy hút khử mùi công nghiệp': 'Máy hút khử mùi công nghiệp',
'Giấy dán kính': 'Giấy dán kính',
'Nồi nấu phở công nghiệp': 'Nồi nấu phở công nghiệp',
'Xô, thùng, chậu nhựa': 'Xô, thùng, chậu nhựa',
'Xe đạp trẻ em': 'Xe đạp trẻ em',
'Máy bơm chữa cháy': 'Máy bơm chữa cháy',
'Sơn nội thất': 'Sơn nội thất',
'Bơm định lượng': 'Bơm định lượng',
'Bình đựng nước': 'Bình đựng nước',
'Dụng cụ xây dựng cầm tay': 'Dụng cụ xây dựng cầm tay',
'Cảm biến Ô tô': 'Cảm biến Ô tô',
'Bộ quần áo lót nữ': 'Bộ quần áo lót nữ',
'Bàn họp': 'Bàn họp',
'Thìa, dĩa, đũa ...': 'Thìa, dĩa, đũa ...',
'Giày cao gót': 'Giày cao gót',
'Tương đen': 'Tương đen',
'Gạch tự chèn ( gạch block )': 'Gạch tự chèn ( gạch block )',
'Xe máy cũ': 'Xe máy cũ',
'Đèn vách': 'Đèn vách',
'Cửa kính': 'Cửa kính',
'Bếp nướng xúc xích': 'Bếp nướng xúc xích',
'Bố thắng (má phanh) xe máy': 'Bố thắng (má phanh) xe máy',
'Bộ quần áo thể thao nữ': 'Bộ quần áo thể thao nữ',
'Giày trẻ em': 'Giày trẻ em',
'Ghế tập ăn, ghế rung cho bé': 'Ghế tập ăn, ghế rung cho bé',
'Tủ gương': 'Tủ gương',
'Sữa tắm nam': 'Sữa tắm nam',
'Thiết bị báo động chống trộm': 'Thiết bị báo động chống trộm',
'Phụ tùng xe nâng khác': 'Phụ tùng xe nâng khác',
'Máy đóng đai': 'Máy đóng đai',
'Lọc gió Ôtô': 'Lọc gió Ôtô',
'Đèn mâm': 'Đèn mâm',
'Lắc tay nữ': 'Lắc tay nữ',
'Bộ hàn, cắt gió đá': 'Bộ hàn, cắt gió đá',
'Thiết bị đại tu, phục hồi ô tô': 'Thiết bị đại tu, phục hồi ô tô',
'Đồ bơi nữ': 'Đồ bơi nữ',
'Máy cưa xương (máy chặt xương)': 'Máy cưa xương (máy chặt xương)',
'Cân bàn': 'Cân bàn',
'Docking stations (Đế cắm thêm)': 'Docking stations (Đế cắm thêm)',
'Xe đẩy quần áo - dọn phòng': 'Xe đẩy quần áo - dọn phòng',
'Mousepad (Bàn di chuột)': 'Mousepad (Bàn di chuột)',
'Áo thể thao nam': 'Áo thể thao nam',
'Quần shorts nữ': 'Quần shorts nữ',
'Chăn điện': 'Chăn điện',
'Dụng cụ tập bụng': 'Dụng cụ tập bụng',
'Cảo - Vam': 'Cảo - Vam',
'Nguyên liệu làm kem': 'Nguyên liệu làm kem',
'Thép vuông': 'Thép vuông',
'Thiết bị trình chiếu ánh sáng': 'Thiết bị trình chiếu ánh sáng',
'Đồ thờ khác': 'Đồ thờ khác',
'Nắp che ống kính': 'Nắp che ống kính',
'Vỉ nướng': 'Vỉ nướng',
'Kẹp số bàn': 'Kẹp số bàn',
'Cân phân tích': 'Cân phân tích',
'Bồn tắm massage': 'Bồn tắm massage',
'Đèn Flash': 'Đèn Flash',
'Đồ bơi trẻ em': 'Đồ bơi trẻ em',
'Máy bay điều khiển từ xa': 'Máy bay điều khiển từ xa',
'Đồng hồ hàng hiệu nữ': 'Đồng hồ hàng hiệu nữ',
'Hoa quả, trái cây': 'Hoa quả, trái cây',
'Xích đu': 'Xích đu',
'Sản phẩm trị sẹo': 'Sản phẩm trị sẹo',
'Văn phòng phẩm khác': 'Văn phòng phẩm khác',
'Dầu gội đầu nam': 'Dầu gội đầu nam',
'Đầu ghi hình cho camera giám sát': 'Đầu ghi hình cho camera giám sát',
'Trần gỗ': 'Trần gỗ',
'Các loại vật liệu hoàn thiện khác': 'Các loại vật liệu hoàn thiện khác',
'Hóa chất xây dựng': 'Hóa chất xây dựng',
'Dép, Sandal trẻ em': 'Dép, Sandal trẻ em',
'Máy ép trái cây': 'Máy ép trái cây',
'Váy bộ': 'Váy bộ',
'Bộ phòng ngủ': 'Bộ phòng ngủ',
'Đèn năng lượng mặt trời': 'Đèn năng lượng mặt trời',
'Loa ngoài điện thoại': 'Loa ngoài điện thoại',
'Máy xay đá': 'Máy xay đá',
'Dụng cụ massage': 'Dụng cụ massage',
'Kính lúp': 'Kính lúp',
'Khóa điện tử': 'Khóa điện tử',
'Áo thun trẻ em': 'Áo thun trẻ em',
'Thiết bị, linh kiện khác': 'Thiết bị, linh kiện khác',
'Mũ, nón bảo hộ': 'Mũ, nón bảo hộ',
'Van lọc': 'Van lọc',
'Đèn ngủ': 'Đèn ngủ',
'Ghế gội đầu': 'Ghế gội đầu',
'Đĩa hoa quả thờ': 'Đĩa hoa quả thờ',
'Máy đo huyết áp': 'Máy đo huyết áp',
'Dây điện': 'Dây điện',
'Máy hút bụi công nghiệp': 'Máy hút bụi công nghiệp',
'Dàn âm thanh': 'Dàn âm thanh',
'Đồng hồ nước': 'Đồng hồ nước',
'Sản phẩm massage mặt': 'Sản phẩm massage mặt',
'Biến tần': 'Biến tần',
'Đàn Organ': 'Đàn Organ',
'Chậu rửa bát không bàn': 'Chậu rửa bát không bàn',
'Đồ ăn cho bà bầu': 'Đồ ăn cho bà bầu',
'Công tắc đơn': 'Công tắc đơn',
'Dụng cụ trang điểm khác': 'Dụng cụ trang điểm khác',
'Máy nén khí piston': 'Máy nén khí piston',
'Ắc quy': 'Ắc quy',
'Bể bơi mini': 'Bể bơi mini',
'Đồng hồ đo vạn năng': 'Đồng hồ đo vạn năng',
'Máy đánh trứng': 'Máy đánh trứng',
'Dây hàn, cáp hàn': 'Dây hàn, cáp hàn',
'Búa thoát hiểm Ô tô': 'Búa thoát hiểm Ô tô',
'Máy bơm nước gia dụng': 'Máy bơm nước gia dụng',
'Sen cây': 'Sen cây',
'Thước đo độ dày (Dụng cụ đo độ dày)': 'Thước đo độ dày (Dụng cụ đo độ dày)',
'Thiết bị đo ánh sáng': 'Thiết bị đo ánh sáng',
'Nhãn dán': 'Nhãn dán',
'Thú nhồi bông': 'Thú nhồi bông',
'Màn chiếu Projector': 'Màn chiếu Projector',
'Xe đẩy tay': 'Xe đẩy tay',
'Máy cắt sắt': 'Máy cắt sắt',
'Đèn sân vườn': 'Đèn sân vườn',
'Quầy xe lưu động ( quầy bán hàng di động )': 'Quầy xe lưu động ( quầy bán hàng di động )',
'Ống bơm cát': 'Ống bơm cát',
'Cây nội thất': 'Cây nội thất',
'Thực phẩm hỗ trợ điều trị bệnh thận': 'Thực phẩm hỗ trợ điều trị bệnh thận',
'Nhà chung cư': 'Nhà chung cư',
'Máy hút bụi': 'Máy hút bụi',
'Dụng cụ, thiết bị sửa chữa Ôtô': 'Dụng cụ, thiết bị sửa chữa Ôtô',
'Phông chụp ảnh': 'Phông chụp ảnh',
'Máy mài cầm tay': 'Máy mài cầm tay',
'Máy tính Desktop (Công ty lắp ráp)': 'Máy tính Desktop (Công ty lắp ráp)',
'Đồng hồ báo thức, để bàn': 'Đồng hồ báo thức, để bàn',
'Thiết bị cảm ứng phòng tắm': 'Thiết bị cảm ứng phòng tắm',
'Quần áo mặc ở nhà': 'Quần áo mặc ở nhà',
'Đèn pha lê': 'Đèn pha lê',
'Quần áo lặn biển': 'Quần áo lặn biển',
'Máy giám sát bảo vệ': 'Máy giám sát bảo vệ',
'Tủ lạnh': 'Tủ lạnh',
'Van bi': 'Van bi',
'Đầu đọc thẻ nhớ': 'Đầu đọc thẻ nhớ',
'Phiếu thu, chi': 'Phiếu thu, chi',
'Hoa khô': 'Hoa khô',
'Lắc tay đôi': 'Lắc tay đôi',
'Quần đôi': 'Quần đôi',
'Ruột chăn': 'Ruột chăn',
'Máy bắt muỗi': 'Máy bắt muỗi',
'Bình, thùng đá nhựa': 'Bình, thùng đá nhựa',
'Đế sạc (Dock) cho điện thoại': 'Đế sạc (Dock) cho điện thoại',
'Card mở rộng': 'Card mở rộng',
'Máy thái lát thịt': 'Máy thái lát thịt',
'Dụng cụ tai mũi họng khác': 'Dụng cụ tai mũi họng khác',
'Ổ rắn (SSD) - Solid state drive': 'Ổ rắn (SSD) - Solid state drive',
'Sofa nhà hàng': 'Sofa nhà hàng',
'Máy đếm tần số': 'Máy đếm tần số',
'Đèn chiếu sáng nhà xưởng': 'Đèn chiếu sáng nhà xưởng',
'Điều hòa': 'Điều hòa',
'Xe tải cẩu': 'Xe tải cẩu',
'Ga trải giường': 'Ga trải giường',
'Máy cưa xích': 'Máy cưa xích',
'Chảo': 'Chảo',
'Máy bơm nước công nghiệp': 'Máy bơm nước công nghiệp',
'Máy hàn công nghiệp': 'Máy hàn công nghiệp',
'Tấm Inox': 'Tấm Inox',
'Biển báo giao thông': 'Biển báo giao thông',
'Ba lô học sinh': 'Ba lô học sinh',
'Ví, bóp nữ': 'Ví, bóp nữ',
'Máy chế biến thực phẩm khác': 'Máy chế biến thực phẩm khác',
'Đầu nối Jack': 'Đầu nối Jack',
'Xe bồn': 'Xe bồn',
'Dầu ăn': 'Dầu ăn',
'Đèn chiếu sáng khẩn cấp': 'Đèn chiếu sáng khẩn cấp',
'Đế âm': 'Đế âm',
'Quần bò nam (Jeans)': 'Quần bò nam (Jeans)',
'Xe đầu kéo (Xe container)': 'Xe đầu kéo (Xe container)',
'Máy xay hạt': 'Máy xay hạt',
'Tấm lót bồn cầu ( tấm lót bệ xí )': 'Tấm lót bồn cầu ( tấm lót bệ xí )',
'Hoa trang trí': 'Hoa trang trí',
'Quạt thờ': 'Quạt thờ',
'Mainboard': 'Mainboard',
'Bếp á': 'Bếp á',
'Hộp giảm tốc': 'Hộp giảm tốc',
'Duỡng tóc, tạo kiểu cho nam': 'Duỡng tóc, tạo kiểu cho nam',
'Bạc đạn, Vòng bi, vòng đệm': 'Bạc đạn, Vòng bi, vòng đệm',
'Đàn Ukulele': 'Đàn Ukulele',
'Dụng cụ nẹp DHS-DCS': 'Dụng cụ nẹp DHS-DCS',
'SDH/MSAP': 'SDH/MSAP',
'Lò xông, tinh dầu': 'Lò xông, tinh dầu',
'Áo sơ sinh': 'Áo sơ sinh',
'Thú nhún': 'Thú nhún',
'Đèn pin': 'Đèn pin',
'Kính xem phim 3D (3D Glasses)': 'Kính xem phim 3D (3D Glasses)',
'Lạc': 'Lạc',
'Đèn cao áp': 'Đèn cao áp',
'Giàn giáo': 'Giàn giáo',
'Tập, vở': 'Tập, vở',
'Van giảm áp': 'Van giảm áp',
'Logo, đề can': 'Logo, đề can',
'Ghế phòng họp': 'Ghế phòng họp',
'Máy nước nóng bơm nhiệt': 'Máy nước nóng bơm nhiệt',
'Thực phẩm chức năng khác': 'Thực phẩm chức năng khác',
'Chất tẩy rửa': 'Chất tẩy rửa',
'Gương cầu lồi': 'Gương cầu lồi',
'Đầu socket': 'Đầu socket',
'Tour du lịch Trong nước': 'Tour du lịch Trong nước',
'Lắc tay bạc nữ': 'Lắc tay bạc nữ',
'Đầu thu kỹ thuật số': 'Đầu thu kỹ thuật số',
'Thuốc ép tóc': 'Thuốc ép tóc',
'Tay nắm xe máy': 'Tay nắm xe máy',
'Bộ điều khiển điện tử': 'Bộ điều khiển điện tử',
'Phụ kiện máy ảnh, máy quay': 'Phụ kiện máy ảnh, máy quay',
'Cà phê hạt': 'Cà phê hạt',
'Các loại nước hoa khác': 'Các loại nước hoa khác',
'Tranh dán tường khác': 'Tranh dán tường khác',
'Máy làm lạnh nước': 'Máy làm lạnh nước',
'Cọc tiêu giao thông': 'Cọc tiêu giao thông',
'Gạch bông': 'Gạch bông',
'Máy in nhãn mác': 'Máy in nhãn mác',
'Đồ đựng bút': 'Đồ đựng bút',
'Block điều hòa': 'Block điều hòa',
'Bộ chuyển đổi quang điện (Converter)': 'Bộ chuyển đổi quang điện (Converter)',
'Máy sấy tóc': 'Máy sấy tóc',
'Kem tắm trắng': 'Kem tắm trắng',
'Máy sản xuất đá viên': 'Máy sản xuất đá viên',
'Ô dù': 'Ô dù',
'Hộp, tủ phối quang': 'Hộp, tủ phối quang',
'Que thử y tế': 'Que thử y tế',
'Dụng cụ đo ren': 'Dụng cụ đo ren',
'Ghép hình lâu đài': 'Ghép hình lâu đài',
'Dây Curoa công nghiệp': 'Dây Curoa công nghiệp',
'Các linh kiện khác (máy tính)': 'Các linh kiện khác (máy tính)',
'Giày bóng đá nam': 'Giày bóng đá nam',
'Hoa cưới': 'Hoa cưới',
'Thiết bị đo áp suất': 'Thiết bị đo áp suất',
'Bàn trà đa năng': 'Bàn trà đa năng',
'Váy yếm': 'Váy yếm',
'Máy gia công thanh cái': 'Máy gia công thanh cái',
'Cổng chia, gộp, chuyển tín hiệu (Hình ảnh)': 'Cổng chia, gộp, chuyển tín hiệu (Hình ảnh)',
'Bộ quần áo thể thao nam': 'Bộ quần áo thể thao nam',
'Khăn khách sạn': 'Khăn khách sạn',
'Kẹo mềm, dẻo': 'Kẹo mềm, dẻo',
'Cây Inox': 'Cây Inox',
'Ruột bút bi': 'Ruột bút bi',
'Váy maxi': 'Váy maxi',
'Sản phẩm dành cho ngực': 'Sản phẩm dành cho ngực',
'Phụ kiện bảo hộ lao động': 'Phụ kiện bảo hộ lao động',
'Đèn chùm': 'Đèn chùm',
'Tay vịn cầu thang': 'Tay vịn cầu thang',
'Máy in All in One': 'Máy in All in One',
'Dụng cụ đựng hóa chất': 'Dụng cụ đựng hóa chất',
'Đèn diệt côn trùng': 'Đèn diệt côn trùng',
'Nguyên liệu sản xuất gạch': 'Nguyên liệu sản xuất gạch',
'Bếp hồng ngoại': 'Bếp hồng ngoại',
'Thiết bị phòng sạch': 'Thiết bị phòng sạch',
'Pin laptop': 'Pin laptop',
'Tủ thuốc': 'Tủ thuốc',
'Bột giặt, nước xả cho bé': 'Bột giặt, nước xả cho bé',
'Giá đỡ điện thoại': 'Giá đỡ điện thoại',
'Tủ giám đốc': 'Tủ giám đốc',
'Yên xe máy': 'Yên xe máy',
'Bỉm, quần tã': 'Bỉm, quần tã',
'Bút kẻ lông mày': 'Bút kẻ lông mày',
'Bộ trang điểm': 'Bộ trang điểm',
'Dây lưng (thắt lưng) nữ': 'Dây lưng (thắt lưng) nữ',
'Khóa cửa sử dụng thẻ từ': 'Khóa cửa sử dụng thẻ từ',
'Phụ kiện thiết bị đo, kiểm tra': 'Phụ kiện thiết bị đo, kiểm tra',
'Phụ kiện cáp': 'Phụ kiện cáp',
'Bút kẻ mắt nước': 'Bút kẻ mắt nước',
'Phụ tùng máy đầm': 'Phụ tùng máy đầm',
'Thực phẩm giảm cân chống béo phì': 'Thực phẩm giảm cân chống béo phì',
'Tủ tạo môi trường': 'Tủ tạo môi trường',
'Máy tiệt trùng - Hâm sữa': 'Máy tiệt trùng - Hâm sữa',
'Ê tô': 'Ê tô',
'Ngói': 'Ngói',
'Xe tập đi cho bé': 'Xe tập đi cho bé',
'Lưới địa kỹ thuật, lưới xây dựng': 'Lưới địa kỹ thuật, lưới xây dựng',
'Hoa văn phòng': 'Hoa văn phòng',
'Máy uốn ống thường': 'Máy uốn ống thường',
'Board mạch điều khiển': 'Board mạch điều khiển',
'Chân máy quay': 'Chân máy quay',
'Máy in laser đen trắng': 'Máy in laser đen trắng',
'Ghép hình máy bay': 'Ghép hình máy bay',
'Thiết bị phát sóng wifi trên Ô tô': 'Thiết bị phát sóng wifi trên Ô tô',
'RAM (Desktop)': 'RAM (Desktop)',
'Thùng rác thông minh': 'Thùng rác thông minh',
'Bút cao cấp': 'Bút cao cấp',
'Sản phẩm làm đẹp từ thiên nhiên': 'Sản phẩm làm đẹp từ thiên nhiên',
'Gương phòng tắm': 'Gương phòng tắm',
'Xe đẩy': 'Xe đẩy',
'Cà phê hòa tan': 'Cà phê hòa tan',
'Khung, album ảnh': 'Khung, album ảnh',
'Màn hình': 'Màn hình',
'Đồng phục gia đình': 'Đồng phục gia đình',
'Máy phay gỗ': 'Máy phay gỗ',
'GPS - Hệ thống định vị vệ tinh trên Ô tô': 'GPS - Hệ thống định vị vệ tinh trên Ô tô',
'Chìa lục giác': 'Chìa lục giác',
'Dây thép': 'Dây thép',
'Máy tính bảng (Tablet PC)': 'Máy tính bảng (Tablet PC)',
'Bu lông, tắc kê': 'Bu lông, tắc kê',
'Laptop, Tablet Trung Quốc': 'Laptop, Tablet Trung Quốc',
'Đệm chống va tàu': 'Đệm chống va tàu',
'Bình giữ nóng trà, cafe': 'Bình giữ nóng trà, cafe',
'Dây đai': 'Dây đai',
'Máy ép dầu đậu nành': 'Máy ép dầu đậu nành',
'Áo măng tô nữ': 'Áo măng tô nữ',
'Thước kẹp ( Thước cặp )': 'Thước kẹp ( Thước cặp )',
'Tủ trưng bày thực phẩm': 'Tủ trưng bày thực phẩm',
'Bàn phím Game thủ': 'Bàn phím Game thủ',
'Đồ chơi - Trang trí nội thất Ô tô': 'Đồ chơi - Trang trí nội thất Ô tô',
'Máy tạo Ozone': 'Máy tạo Ozone',
'An toàn cho trẻ': 'An toàn cho trẻ',
'Kẹp tóc, cặp tóc': 'Kẹp tóc, cặp tóc',
'Bản lề': 'Bản lề',
'Phụ kiện Flycam': 'Phụ kiện Flycam',
'Đui đèn các loại': 'Đui đèn các loại',
'Chăm sóc răng miệng': 'Chăm sóc răng miệng',
'Các sản phẩm khác': 'Các sản phẩm khác',
'Dây câu': 'Dây câu',
'Đèn chiếu sáng khuôn viên': 'Đèn chiếu sáng khuôn viên',
'Máy thái rau, củ': 'Máy thái rau, củ',
'Bồn ngâm chân': 'Bồn ngâm chân',
'Bộ liên hoàn trong nhà': 'Bộ liên hoàn trong nhà',
'Máy làm sushi': 'Máy làm sushi',
'Phụ kiện cho tivi': 'Phụ kiện cho tivi',
'Thiết bị làm sạch': 'Thiết bị làm sạch',
'Phụ kiện máy chơi Game': 'Phụ kiện máy chơi Game',
'Buộc tóc trẻ em': 'Buộc tóc trẻ em',
'Máy phun thuốc khử trùng': 'Máy phun thuốc khử trùng',
'Đồ ăn không béo, ăn kiêng': 'Đồ ăn không béo, ăn kiêng',
'Ba lô leo núi, du lịch': 'Ba lô leo núi, du lịch',
'Vè che mưa Ôtô': 'Vè che mưa Ôtô',
'Dụng cụ bóng chuyền': 'Dụng cụ bóng chuyền',
'Thực phẩm phòng bệnh, tăng sức đề kháng': 'Thực phẩm phòng bệnh, tăng sức đề kháng',
'Máy bơm bể bơi': 'Máy bơm bể bơi',
'Khung tranh': 'Khung tranh',
'Cup, huy chương, biểu trưng': 'Cup, huy chương, biểu trưng',
'Máng đèn': 'Máng đèn',
'Cồn công nghiệp': 'Cồn công nghiệp',
'Máy khoan, đục bê tông': 'Máy khoan, đục bê tông',
'Quần trẻ em': 'Quần trẻ em',
'Vỏ máy điện thoại': 'Vỏ máy điện thoại',
'Đồng hồ so': 'Đồng hồ so',
'Sữa nước': 'Sữa nước',
'Thớt, rế, lót tay ...': 'Thớt, rế, lót tay ...',
'Máy tách, bóc vỏ thực phẩm': 'Máy tách, bóc vỏ thực phẩm',
'Phần mềm Mobile, PDA': 'Phần mềm Mobile, PDA',
'Bục phát biểu': 'Bục phát biểu',
'Dịch vụ tháo dỡ và di chuyển': 'Dịch vụ tháo dỡ và di chuyển',
'Ốp - Cản - Bậc': 'Ốp - Cản - Bậc',
'Keo công nghiệp': 'Keo công nghiệp',
'Thời trang nam khác': 'Thời trang nam khác',
'Đồ vệ sinh, bàn chải, khăn': 'Đồ vệ sinh, bàn chải, khăn',
'Giá, kệ để đồ trẻ em': 'Giá, kệ để đồ trẻ em',
'Mỡ công nghiệp': 'Mỡ công nghiệp',
'Sơn chống thấm': 'Sơn chống thấm',
'Áo khoác thể thao nữ': 'Áo khoác thể thao nữ',
'Loa trong laptop': 'Loa trong laptop',
'Thiết bị đo độ ẩm': 'Thiết bị đo độ ẩm',
'Phụ kiện teen nam': 'Phụ kiện teen nam',
'Kính hiển vi phẫu thuật': 'Kính hiển vi phẫu thuật',
'Máy xông hơi mặt': 'Máy xông hơi mặt',
'Đèn bể bơi': 'Đèn bể bơi',
'Cỏ nhân tạo': 'Cỏ nhân tạo',
'Thực phẩm hỗ trợ làm đẹp da, tóc': 'Thực phẩm hỗ trợ làm đẹp da, tóc',
'Ống gió': 'Ống gió',
'Loa máy tính': 'Loa máy tính',
'Xe lu': 'Xe lu',
'Bìa': 'Bìa',
'Dụng cụ nha khoa': 'Dụng cụ nha khoa',
'Vòi hoa sen khác': 'Vòi hoa sen khác',
'Giày gót thấp': 'Giày gót thấp',
'Vali, Hành lý': 'Vali, Hành lý',
'Cáp đồng trục': 'Cáp đồng trục',
'Băng keo chịu lực': 'Băng keo chịu lực',
'Tivi LED': 'Tivi LED',
'Thìa, dĩa cho bé': 'Thìa, dĩa cho bé',
'Phụ kiện khí nén': 'Phụ kiện khí nén',
'Đồ hộp': 'Đồ hộp',
'Bluetooth USB Adapter': 'Bluetooth USB Adapter',
'Chậu rửa bát có bàn': 'Chậu rửa bát có bàn',
'Sản phẩm làm trắng': 'Sản phẩm làm trắng',
'Tủ Lavabo': 'Tủ Lavabo',
'Bộ típ ( bộ tuýp )': 'Bộ típ ( bộ tuýp )',
'Đèn ôtô': 'Đèn ôtô',
'Lưới an toàn': 'Lưới an toàn',
'Sạc pin laptop (Adapter)': 'Sạc pin laptop (Adapter)',
'Xe đẩy, giá thức ăn': 'Xe đẩy, giá thức ăn',
'Phụ kiện trang trí xe máy': 'Phụ kiện trang trí xe máy',
'Vật tư y tế khác': 'Vật tư y tế khác',
'Túi Hand-made': 'Túi Hand-made',
'Chỉ phẫu thuật': 'Chỉ phẫu thuật',
'Robot cấp phôi tự động': 'Robot cấp phôi tự động',
'Máy dò kim loại công nghiệp': 'Máy dò kim loại công nghiệp',
'Bộ mỹ phẩm chăm sóc tóc': 'Bộ mỹ phẩm chăm sóc tóc',
'Cua biển - Ghẹ biển': 'Cua biển - Ghẹ biển',
'Hot Deal Spa, sức khỏe': 'Hot Deal Spa, sức khỏe',
'Nồi cơm điện': 'Nồi cơm điện',
'Dịch vụ thẩm mỹ': 'Dịch vụ thẩm mỹ',
'Phụ kiện thiết bị điện khác': 'Phụ kiện thiết bị điện khác',
'Tiêu, Sáo': 'Tiêu, Sáo',
'Thang': 'Thang',
'Vật liệu cách âm, cách nhiệt': 'Vật liệu cách âm, cách nhiệt',
'Mặt nạ bảo hộ': 'Mặt nạ bảo hộ',
'Máy bơm hút dầu, mỡ': 'Máy bơm hút dầu, mỡ',
'Nguyên liệu tá dược': 'Nguyên liệu tá dược',
'Đèn sưởi': 'Đèn sưởi',
'Ván trượt - SkateBoard': 'Ván trượt - SkateBoard',
'Sản phẩm chăm sóc tóc': 'Sản phẩm chăm sóc tóc',
'Máy ép nhựa': 'Máy ép nhựa',
'Khẩu trang': 'Khẩu trang',
'Dây lưng, đai an toàn': 'Dây lưng, đai an toàn',
'Máy làm đá siêu tốc': 'Máy làm đá siêu tốc',
'Khóa cửa bằng vân tay': 'Khóa cửa bằng vân tay',
'Dụng cụ, thiết bị sửa chữa Xe máy': 'Dụng cụ, thiết bị sửa chữa Xe máy',
'Khuôn mẫu các loại': 'Khuôn mẫu các loại',
'Thuốc bổ, Vitamin': 'Thuốc bổ, Vitamin',
'Pa Lăng': 'Pa Lăng',
'Bộ quần áo nam': 'Bộ quần áo nam',
'Phụ kiện máy nén khí khác': 'Phụ kiện máy nén khí khác',
'Bơm hút chân không': 'Bơm hút chân không',
'Ắc quy xe máy': 'Ắc quy xe máy',
'Phụ kiện cho thiết bị mạng': 'Phụ kiện cho thiết bị mạng',
'Tất nam': 'Tất nam',
'Pin máy ảnh, máy quay': 'Pin máy ảnh, máy quay',
'Nhẫn nam': 'Nhẫn nam',
'Mũ, nón nữ': 'Mũ, nón nữ',
'Chuyển phát nhanh': 'Chuyển phát nhanh',
'Quần legging': 'Quần legging',
'Đồng hồ treo tường': 'Đồng hồ treo tường',
'Dụng cụ cố định ngoài xương': 'Dụng cụ cố định ngoài xương',
'Máy tiện CNC': 'Máy tiện CNC',
'Miếng dán trắng răng': 'Miếng dán trắng răng',
'Rau, củ, quả': 'Rau, củ, quả',
'Tủ đựng đồ phòng ngủ': 'Tủ đựng đồ phòng ngủ',
'Nam châm': 'Nam châm',
'Thiết bị xông hơi khô': 'Thiết bị xông hơi khô',
'Máy hút ẩm': 'Máy hút ẩm',
'Máy cắt Plasma': 'Máy cắt Plasma',
'Thực phẩm khô khác': 'Thực phẩm khô khác',
'Máy ép màng nhôm': 'Máy ép màng nhôm',
'Thiết bị bảo dưỡng ô tô': 'Thiết bị bảo dưỡng ô tô',
'Máy dán miệng cốc': 'Máy dán miệng cốc',
'Bánh khác': 'Bánh khác',
'Đồng hồ hàng hiệu khác': 'Đồng hồ hàng hiệu khác',
'Xe quét rác': 'Xe quét rác',
'Xe máy phân khối lớn (Motor)': 'Xe máy phân khối lớn (Motor)',
'Điện thoại Trung Quốc': 'Điện thoại Trung Quốc',
'Áo sơ mi trẻ em': 'Áo sơ mi trẻ em',
'Máy cắt nhôm': 'Máy cắt nhôm',
'Tampon, dấu, mực dấu': 'Tampon, dấu, mực dấu',
'Biến áp máy cấp nguồn đa năng': 'Biến áp máy cấp nguồn đa năng',
'Chậu rửa Lavabo treo tường': 'Chậu rửa Lavabo treo tường',
'Giày tennis nam': 'Giày tennis nam',
'Cầu trượt': 'Cầu trượt',
'Đồ bảo vệ, phụ kiện bóng đá': 'Đồ bảo vệ, phụ kiện bóng đá',
'Chăn': 'Chăn',
'Hộp đựng giấy phòng tắm': 'Hộp đựng giấy phòng tắm',
'Sản phẩm phòng chống côn trùng': 'Sản phẩm phòng chống côn trùng',
'Bộ chổi trang điểm': 'Bộ chổi trang điểm',
'Quần yếm': 'Quần yếm',
'Quần giả váy': 'Quần giả váy',
'Bàn chế biến thực phẩm': 'Bàn chế biến thực phẩm',
'Power Amplifier': 'Power Amplifier',
'Chai, lọ, can': 'Chai, lọ, can',
'Tấm mặt chống tràn bể bơi': 'Tấm mặt chống tràn bể bơi',
'Mũ, nón sơ sinh': 'Mũ, nón sơ sinh',
'Sổ': 'Sổ',
'Dụng cụ cho vật nuôi': 'Dụng cụ cho vật nuôi',
'Máy cắt laser': 'Máy cắt laser',
'Van khí nén': 'Van khí nén',
'Cá khô': 'Cá khô',
'Van cầu': 'Van cầu',
'Máy mài khuôn': 'Máy mài khuôn',
'Thuốc nhuộm tóc': 'Thuốc nhuộm tóc',
'Giàn năng lượng mặt trời ( Máy nước nóng năng lượng mặt trời )': 'Giàn năng lượng mặt trời ( Máy nước nóng năng lượng mặt trời )',
'Mồi câu': 'Mồi câu',
'Bộ thiết bị phòng tắm': 'Bộ thiết bị phòng tắm',
'Vòng bi xe nâng': 'Vòng bi xe nâng',
'Bút kẻ viền môi': 'Bút kẻ viền môi',
'Áo da nữ': 'Áo da nữ',
'Que hàn , thau hàn': 'Que hàn , thau hàn',
'Thang nâng': 'Thang nâng',
'Túi cứu thương': 'Túi cứu thương',
'Sản phẩm dành riêng cho nam': 'Sản phẩm dành riêng cho nam',
'Máy ghi âm': 'Máy ghi âm',
'Đệm (Nệm) cho bé': 'Đệm (Nệm) cho bé',
'Cửa đi mở quay ra ngoài': 'Cửa đi mở quay ra ngoài',
'Máy cắt cỏ': 'Máy cắt cỏ',
'Bộ điều khiển nguồn điện': 'Bộ điều khiển nguồn điện',
'Túi đựng đồ cho bé': 'Túi đựng đồ cho bé',
'Đầu nối nhanh khí nén': 'Đầu nối nhanh khí nén',
'Nhẫn cưới, nhẫn đính hôn': 'Nhẫn cưới, nhẫn đính hôn',
'Sơn ngoại thất': 'Sơn ngoại thất',
'Máy khác': 'Máy khác',
'Bông trang điểm': 'Bông trang điểm',
'Yếm ăn cho bé': 'Yếm ăn cho bé',
'Máy đập lúa': 'Máy đập lúa',
'Áo gió nữ': 'Áo gió nữ',
'Bộ đèn trang trí': 'Bộ đèn trang trí',
'Thanh treo khăn đơn': 'Thanh treo khăn đơn',
'Giá, móc treo quần áo': 'Giá, móc treo quần áo',
'Video Card': 'Video Card',
'Kéo': 'Kéo',
'Mua xe trả góp': 'Mua xe trả góp',
'Mũ (Nón) bảo hiểm xe đạp': 'Mũ (Nón) bảo hiểm xe đạp',
'Trang phục bảo hiểm xe máy': 'Trang phục bảo hiểm xe máy',
'Cây giả - Hoa giả nghệ thuật': 'Cây giả - Hoa giả nghệ thuật',
'Gạch lát nền': 'Gạch lát nền',
'Ấm siêu tốc': 'Ấm siêu tốc',
'Tông đơ cắt tóc': 'Tông đơ cắt tóc',
'Bộ trang sức, nữ trang': 'Bộ trang sức, nữ trang',
'Phụ kiện mạng': 'Phụ kiện mạng',
'Quần áo ngủ nam': 'Quần áo ngủ nam',
'Bình uống nước cho bé': 'Bình uống nước cho bé',
'Mô tơ máy bơm': 'Mô tơ máy bơm',
'Thuốc an thần': 'Thuốc an thần',
'Phụ kiện máy phun sương': 'Phụ kiện máy phun sương',
'CPU Server': 'CPU Server',
'Sàn nhẹ': 'Sàn nhẹ',
'Tivi Plasma': 'Tivi Plasma',
'Vách ngăn phòng khách': 'Vách ngăn phòng khách',
'Thùng sau Xe máy': 'Thùng sau Xe máy',
'Phụ kiện, thiết bị Tennis': 'Phụ kiện, thiết bị Tennis',
'Máy đếm tiền': 'Máy đếm tiền',
'Ống dẫn hơi': 'Ống dẫn hơi',
'Đồng hồ đeo tay Hồng Kông trẻ em': 'Đồng hồ đeo tay Hồng Kông trẻ em',
'Bàn chơi game - Bàn phòng Game': 'Bàn chơi game - Bàn phòng Game',
'Sữa tắm, dầu gội đầu cho bé': 'Sữa tắm, dầu gội đầu cho bé',
'Tour du lịch Châu Á': 'Tour du lịch Châu Á',
'Tranh tường (Graffiti)': 'Tranh tường (Graffiti)',
'Bơm nước Ôtô': 'Bơm nước Ôtô',
'Gối trang trí': 'Gối trang trí',
'Đỉnh thờ': 'Đỉnh thờ',
'Bồn nước': 'Bồn nước',
'Hoa tình yêu': 'Hoa tình yêu',
'Mực khô': 'Mực khô',
'Dây dẫn Hi-End': 'Dây dẫn Hi-End',
'Xe nâng': 'Xe nâng',
'Chặn lùi xe, định vị bánh xe': 'Chặn lùi xe, định vị bánh xe',
'Sản phẩm dùng một lần': 'Sản phẩm dùng một lần',
'Loa che nắng (Hood)': 'Loa che nắng (Hood)',
'Thiết bị dạy và học các cấp': 'Thiết bị dạy và học các cấp',
'Máy cưa vanh': 'Máy cưa vanh',
'Gáy lò xo đóng sổ': 'Gáy lò xo đóng sổ',
'Barie tự động': 'Barie tự động',
'Vít': 'Vít',
'Máy nén khí': 'Máy nén khí',
'Logo, poster, đề can': 'Logo, poster, đề can',
'Đèn rọi': 'Đèn rọi',
'Gói cước 3G': 'Gói cước 3G',
'Động cơ nổ': 'Động cơ nổ',
'Đàn Violin (Vĩ cầm)': 'Đàn Violin (Vĩ cầm)',
'Cân điện tử khác': 'Cân điện tử khác',
'Khay, hộp tre': 'Khay, hộp tre',
'Nắp xăng Ô tô': 'Nắp xăng Ô tô',
'Bộ trống': 'Bộ trống',
'Dung dịch xả': 'Dung dịch xả',
'Kem lót': 'Kem lót',
'Máy in mã vạch': 'Máy in mã vạch',
'Đầu nối ( cho ống luồn dây điện )': 'Đầu nối ( cho ống luồn dây điện )',
'Phụ gia xây dựng': 'Phụ gia xây dựng',
'Thước đo lỗ': 'Thước đo lỗ',
'Đồ chơi trong giáo dục': 'Đồ chơi trong giáo dục',
'Súng bắn đinh': 'Súng bắn đinh',
'Thời trang cho vật nuôi': 'Thời trang cho vật nuôi',
'Dụng cụ niêm phong hàng hóa': 'Dụng cụ niêm phong hàng hóa',
'Thuốc tiểu đường': 'Thuốc tiểu đường',
'Các loại kem phấn cho bé': 'Các loại kem phấn cho bé',
'Sạc điện, chuyển đổi điện': 'Sạc điện, chuyển đổi điện',
'Gối ôm': 'Gối ôm',
'Switches - Chuyển mạch': 'Switches - Chuyển mạch',
'Tivi LCD': 'Tivi LCD',
'Máy cắt CNC': 'Máy cắt CNC',
'HDD 3.5 Inch (Ổ cứng Desktop)': 'HDD 3.5 Inch (Ổ cứng Desktop)',
'Bao bì thực phẩm': 'Bao bì thực phẩm',
'Vải lọc chống tĩnh điện': 'Vải lọc chống tĩnh điện',
'Phụ kiện thời trang': 'Phụ kiện thời trang',
'Thước xếp': 'Thước xếp',
'Máy xóa xăm': 'Máy xóa xăm',
'Mỹ phẩm tạo dáng tóc': 'Mỹ phẩm tạo dáng tóc',
'Đồ chơi thể thao cho trẻ khác': 'Đồ chơi thể thao cho trẻ khác',
'Phụ kiện sách điện tử (Ebook Reader Accessories)': 'Phụ kiện sách điện tử (Ebook Reader Accessories)',
'Phụ kiện cân điện tử': 'Phụ kiện cân điện tử',
'Bể rửa siêu âm': 'Bể rửa siêu âm',
'Quạt sạc': 'Quạt sạc',
'Thiết bị vệ sinh bể bơi': 'Thiết bị vệ sinh bể bơi',
'Quần tây nữ': 'Quần tây nữ',
'Nhân sâm khô': 'Nhân sâm khô',
'Phòng thay đồ di động': 'Phòng thay đồ di động',
'Phụ kiện máy chế biến gỗ': 'Phụ kiện máy chế biến gỗ',
'Cổng từ kiểm soát ra vào': 'Cổng từ kiểm soát ra vào',
'Sofa giường': 'Sofa giường',
'Quần áo tập luyện, thi đấu (golf)': 'Quần áo tập luyện, thi đấu (golf)',
'Gel bôi trơn': 'Gel bôi trơn',
'Bộ đồ chế biến ăn dặm cho bé': 'Bộ đồ chế biến ăn dặm cho bé',
'Nấm': 'Nấm',
'Mật ong': 'Mật ong',
'Máy băm rau cỏ cho gia súc, gia cầm': 'Máy băm rau cỏ cho gia súc, gia cầm',
'Dịch vụ luật khác': 'Dịch vụ luật khác',
'Các loại máy khác': 'Các loại máy khác',
'Hệ thống xử lý bụi, thông gió': 'Hệ thống xử lý bụi, thông gió',
'Gioăng cửa': 'Gioăng cửa',
'Giấy ướt, giấy lót xu...': 'Giấy ướt, giấy lót xu...',
'Máy tháo lắp lốp Ôtô': 'Máy tháo lắp lốp Ôtô',
'Bình nóng lạnh': 'Bình nóng lạnh',
'Khóa chống trộm xe máy': 'Khóa chống trộm xe máy',
'Cáp kết nối tivi': 'Cáp kết nối tivi',
'Dầu, nhớt, dung dịch bảo dưỡng': 'Dầu, nhớt, dung dịch bảo dưỡng',
'Máy ảnh số': 'Máy ảnh số',
'Đồ chơi ghép hình khác': 'Đồ chơi ghép hình khác',
'Sản phẩm chăm sóc da tay': 'Sản phẩm chăm sóc da tay',
'Thanh Cân Bằng Ôtô': 'Thanh Cân Bằng Ôtô',
'Các loại phần mềm khác': 'Các loại phần mềm khác',
'Dây phao bể bơi': 'Dây phao bể bơi',
'Thước đo độ sâu': 'Thước đo độ sâu',
'Bột đá (CaCO3)': 'Bột đá (CaCO3)',
'Che khuyết điểm': 'Che khuyết điểm',
'Bơm ly tâm': 'Bơm ly tâm',
'Đồ dùng khác cho bé': 'Đồ dùng khác cho bé',
'Ghế xếp Folding': 'Ghế xếp Folding',
'Máy hàn ống': 'Máy hàn ống',
'Thạch trái cây': 'Thạch trái cây',
'Tương hột': 'Tương hột',
'Ống luồn dây điện': 'Ống luồn dây điện',
'Áo dài nam': 'Áo dài nam',
'Quần áo khiêu vũ nam': 'Quần áo khiêu vũ nam',
'Tất trẻ em': 'Tất trẻ em',
'Máy rung khí nén': 'Máy rung khí nén',
'Cân sức khoẻ': 'Cân sức khoẻ',
'Ruột gối': 'Ruột gối',
'Thiết bị cảm biến': 'Thiết bị cảm biến',
'Dụng cụ dán mi': 'Dụng cụ dán mi',
'Nguyên liệu sản xuất thực phẩm': 'Nguyên liệu sản xuất thực phẩm',
'Dung dịch vệ sinh phụ nữ': 'Dung dịch vệ sinh phụ nữ',
'Máy giặt công nghiệp': 'Máy giặt công nghiệp',
'Bếp nướng': 'Bếp nướng',
'Đặc sản miền Nam': 'Đặc sản miền Nam',
'Máy tháo lắp lốp xe máy': 'Máy tháo lắp lốp xe máy',
'Bệ bước Ôtô': 'Bệ bước Ôtô',
'Phụ kiện và vật liệu': 'Phụ kiện và vật liệu',
'Vật liệu lọc nước': 'Vật liệu lọc nước',
'Phụ kiện thiết bị làm sạch': 'Phụ kiện thiết bị làm sạch',
'Rơ Moóc': 'Rơ Moóc',
'Máy taro (Máy khoan tạo ren)': 'Máy taro (Máy khoan tạo ren)',
'Các vật tư phụ': 'Các vật tư phụ',
'Ốp chân phanh, ga': 'Ốp chân phanh, ga',
'Máy phun sương tăng độ ẩm': 'Máy phun sương tăng độ ẩm',
'Tủ lạnh phòng thí nghiệm': 'Tủ lạnh phòng thí nghiệm',
'Hệ thống xử lý chất thải': 'Hệ thống xử lý chất thải',
'Máy cắt khuôn mẫu may công nghiệp': 'Máy cắt khuôn mẫu may công nghiệp',
'Lịch': 'Lịch',
'Cột nước, vòi phun': 'Cột nước, vòi phun',
'Cao su công nghiệp': 'Cao su công nghiệp',
'Máy đùn ép cám viên': 'Máy đùn ép cám viên',
'Kéo cắt công nghiệp': 'Kéo cắt công nghiệp',
'Máy rửa bát': 'Máy rửa bát',
'Van máy nén khí': 'Van máy nén khí',
'Máy thùa khuy': 'Máy thùa khuy',
'Thiệp cưới': 'Thiệp cưới',
'Gối ô tô': 'Gối ô tô',
'Đồ chơi laptop': 'Đồ chơi laptop',
'Cảm biến nhiệt độ': 'Cảm biến nhiệt độ',
'Gương đèn trang trí': 'Gương đèn trang trí',
'Gương, kính ô tô': 'Gương, kính ô tô',
'Máy dán nhãn tự động': 'Máy dán nhãn tự động',
'Phụ kiện nhạc cụ': 'Phụ kiện nhạc cụ',
'USB Memory 3.0': 'USB Memory 3.0',
'Trạm trộn bê tông': 'Trạm trộn bê tông',
'Ắc quy ô tô': 'Ắc quy ô tô',
'Pin và phụ kiện': 'Pin và phụ kiện',
'Dao rọc giấy': 'Dao rọc giấy',
'Quần áo bóng đá nam': 'Quần áo bóng đá nam',
'Snack': 'Snack',
'Thang máy': 'Thang máy',
'Sữa bột': 'Sữa bột',
'Đá điêu khắc': 'Đá điêu khắc',
'USB Modem - USB 3G': 'USB Modem - USB 3G',
'Bếp rán': 'Bếp rán',
'Công tắc hành trình': 'Công tắc hành trình',
'Bồn rửa y tế': 'Bồn rửa y tế',
'Ghế chơi game - Ghế phòng game': 'Ghế chơi game - Ghế phòng game',
'Cầu thang gỗ': 'Cầu thang gỗ',
'Thùng, vỏ máy tính (PC Case)': 'Thùng, vỏ máy tính (PC Case)',
'Cầu nâng': 'Cầu nâng',
'Quần tây': 'Quần tây',
'Vest nam': 'Vest nam',
'Chìa khóa (Remote) Ôtô': 'Chìa khóa (Remote) Ôtô',
'Bệt Toilet tự động': 'Bệt Toilet tự động',
'Wax Tẩy lông': 'Wax Tẩy lông',
'Sản phẩm massage toàn thân': 'Sản phẩm massage toàn thân',
'Tủ chống ẩm': 'Tủ chống ẩm',
'Cáp điện': 'Cáp điện',
'Mũ, nón trẻ em': 'Mũ, nón trẻ em',
'Cho thuê trang thiết bị tổ chức sự kiện': 'Cho thuê trang thiết bị tổ chức sự kiện',
'Máy tạo Ozone công nghiệp': 'Máy tạo Ozone công nghiệp',
'Chì hàn, thiếc hàn': 'Chì hàn, thiếc hàn',
'Vỏ chăn': 'Vỏ chăn',
'Nắp thùng sau Ô tô': 'Nắp thùng sau Ô tô',
'Thiết bị siêu thị': 'Thiết bị siêu thị',
'Bạt, mái che': 'Bạt, mái che',
'Van các loại ( dùng cho bể bơi )': 'Van các loại ( dùng cho bể bơi )',
'Dụng cụ tập luyện, thi đấu (võ thuật, yoga)': 'Dụng cụ tập luyện, thi đấu (võ thuật, yoga)',
'Túi xách teen nữ': 'Túi xách teen nữ',
'Phụ tùng ôtô': 'Phụ tùng ôtô',
'Ổ quang laptop': 'Ổ quang laptop',
'Ghim bấm': 'Ghim bấm',
'Cáp màn hình laptop': 'Cáp màn hình laptop',
'Món Cá': 'Món Cá',
'Điện thoại trả góp': 'Điện thoại trả góp',
'Nồi hấp': 'Nồi hấp',
'Túi lọc bụi': 'Túi lọc bụi',
'Máy làm đẹp da': 'Máy làm đẹp da',
'Biển, bảng, đèn thông báo ( Led )': 'Biển, bảng, đèn thông báo ( Led )',
'Thuốc uốn tóc': 'Thuốc uốn tóc',
'Xe máy ba bánh chở hàng': 'Xe máy ba bánh chở hàng',
'Máy đo độ cứng': 'Máy đo độ cứng',
'Bồn tắm góc massage': 'Bồn tắm góc massage',
'Bơm tay thủy lực': 'Bơm tay thủy lực',
'Dịch vụ câu cá': 'Dịch vụ câu cá',
'Bộ Timer hẹn giờ': 'Bộ Timer hẹn giờ',
'Bộ phụ kiện phòng tắm': 'Bộ phụ kiện phòng tắm',
'Sạc pin máy ảnh, máy quay': 'Sạc pin máy ảnh, máy quay',
'Thiết bị xông hơi ướt': 'Thiết bị xông hơi ướt',
'Thiết bị thu nước bể bơi': 'Thiết bị thu nước bể bơi',
'Đồng hồ đo lưu lượng': 'Đồng hồ đo lưu lượng',
'Cốp pha': 'Cốp pha',
'Bản lề laptop': 'Bản lề laptop',
'Còi ô tô': 'Còi ô tô',
'Sàn nhựa, gạch nhựa': 'Sàn nhựa, gạch nhựa',
'Chuông, còi báo cháy': 'Chuông, còi báo cháy',
'Vật dụng liên quan bóng rổ': 'Vật dụng liên quan bóng rổ',
'Manơ Canh': 'Manơ Canh',
'Bảng điện tử': 'Bảng điện tử',
'Ống thoát hiểm': 'Ống thoát hiểm',
'Máy massage toàn thân': 'Máy massage toàn thân',
'Lưới giặt': 'Lưới giặt',
'Máy cân bằng tia Laser': 'Máy cân bằng tia Laser',
'Vòng tay trẻ em': 'Vòng tay trẻ em',
'Cây nước nóng lạnh': 'Cây nước nóng lạnh',
'Nguyên liệu, phụ kiện khác': 'Nguyên liệu, phụ kiện khác',
'Projector (máy chiếu)': 'Projector (máy chiếu)',
'Phụ tùng bơm bê tông': 'Phụ tùng bơm bê tông',
'Máy ảnh số chuyên dụng': 'Máy ảnh số chuyên dụng',
'Xe đi chợ': 'Xe đi chợ',
'Nhà bóng, bể vầy': 'Nhà bóng, bể vầy',
'Thực phẩm dinh dưỡng tăng cân': 'Thực phẩm dinh dưỡng tăng cân',
'Linh kiện, phụ kiện đồ chơi': 'Linh kiện, phụ kiện đồ chơi',
'Kèn Saxophone': 'Kèn Saxophone',
'Đồng hồ cổ': 'Đồng hồ cổ',
'Ống nhòm': 'Ống nhòm',
'Máy hàn CO2/MAG': 'Máy hàn CO2/MAG',
'Đai cột sống': 'Đai cột sống',
'Phụ kiện, thiết bị Cầu lông': 'Phụ kiện, thiết bị Cầu lông',
'Máy làm kem': 'Máy làm kem',
'Khăn trải bàn, khăn ăn ...': 'Khăn trải bàn, khăn ăn ...',
'Dụng cụ thể hình khác': 'Dụng cụ thể hình khác',
'Tỏi khô': 'Tỏi khô',
'Súng xiết Bu lông': 'Súng xiết Bu lông',
'Máy đo nhiệt độ': 'Máy đo nhiệt độ',
'Kính lúp công nghiệp': 'Kính lúp công nghiệp',
'Nến thờ': 'Nến thờ',
'Bồn tắm nằm (bồn ngâm)': 'Bồn tắm nằm (bồn ngâm)',
'Máy pha cafe': 'Máy pha cafe',
'Địu bé': 'Địu bé',
'Dụng cụ tập luyện võ thuật': 'Dụng cụ tập luyện võ thuật',
'Máy viền chỉ': 'Máy viền chỉ',
'Hệ giàn thép': 'Hệ giàn thép',
'Hạt mạng (Conector)': 'Hạt mạng (Conector)',
'Chiếu': 'Chiếu',
'Các thiết bị tản nhiệt': 'Các thiết bị tản nhiệt',
'Giấy công nghiệp': 'Giấy công nghiệp',
'Váy liền': 'Váy liền',
'Kìm bấm cáp': 'Kìm bấm cáp',
'Tranh chữ': 'Tranh chữ',
'Phụ kiện bể bơi khác': 'Phụ kiện bể bơi khác',
'Máy vát mép': 'Máy vát mép',
'Nồi hơi': 'Nồi hơi',
'Cửa tự động': 'Cửa tự động',
'Đá , Cát': 'Đá , Cát',
'Sửa chữa, bảo dưỡng, lắp đặt': 'Sửa chữa, bảo dưỡng, lắp đặt',
'Máy thổi khí': 'Máy thổi khí',
'Sản phẩm chăm sóc vật nuôi': 'Sản phẩm chăm sóc vật nuôi',
'Búa cầm tay': 'Búa cầm tay',
'Xà đơn': 'Xà đơn',
'Thiết bị viễn thông khác': 'Thiết bị viễn thông khác',
'Tủ hút khí độc': 'Tủ hút khí độc',
'Sách điện tử ( eBook Readers )': 'Sách điện tử ( eBook Readers )',
'Quần lót trẻ em': 'Quần lót trẻ em',
'Sên nhông đĩa': 'Sên nhông đĩa',
'Máy ép dầu thực vật': 'Máy ép dầu thực vật',
'Đá cắt': 'Đá cắt',
'Mặt dây chuyền nữ': 'Mặt dây chuyền nữ',
'Receiver': 'Receiver',
'Phục trang nam khác': 'Phục trang nam khác',
'Phanh,Má phanh Ôtô': 'Phanh,Má phanh Ôtô',
'Gối cho bé': 'Gối cho bé',
'Gạch trang trí': 'Gạch trang trí',
'Chuồng, cũi cho vật nuôi': 'Chuồng, cũi cho vật nuôi',
'Máy thông tắc ( ống, cống )': 'Máy thông tắc ( ống, cống )',
'Bộ ga và đệm cho cũi': 'Bộ ga và đệm cho cũi',
'Chuông cửa': 'Chuông cửa',
'HDD box': 'HDD box',
'Máy hiện sóng': 'Máy hiện sóng',
'Ống dẫn xăng dầu': 'Ống dẫn xăng dầu',
'Xà bông': 'Xà bông',
'Thiết bị ghi âm bộ đàm': 'Thiết bị ghi âm bộ đàm',
'Nguyên liệu làm bánh các loại': 'Nguyên liệu làm bánh các loại',
'Bộ chia màn hình': 'Bộ chia màn hình',
'Đồ trang trí gốm, sứ': 'Đồ trang trí gốm, sứ',
'Giá vẽ cho bé': 'Giá vẽ cho bé',
'Tời kéo': 'Tời kéo',
'Van công nghiệp khác': 'Van công nghiệp khác',
'Máy in khổ lớn': 'Máy in khổ lớn',
'Bể cá': 'Bể cá',
'Máy làm mát di động': 'Máy làm mát di động',
'Phần mềm cho Windows': 'Phần mềm cho Windows',
'Cáp usb - USB cable': 'Cáp usb - USB cable',
'Quạt cây': 'Quạt cây',
'Vận tải nội địa': 'Vận tải nội địa',
'Máy khò': 'Máy khò',
'Bánh kem xốp': 'Bánh kem xốp',
'Bộ cờ lê': 'Bộ cờ lê',
'Đèn báo sự cố ( dùng trong pccc )': 'Đèn báo sự cố ( dùng trong pccc )',
'Đèn giao thông': 'Đèn giao thông',
'Dây chuyền nam': 'Dây chuyền nam',
'Đồ chơi bập bênh': 'Đồ chơi bập bênh',
'Đường': 'Đường',
'Quần áo bóng rổ': 'Quần áo bóng rổ',
'Nguyên liệu, hương liệu thực phẩm': 'Nguyên liệu, hương liệu thực phẩm',
'Cá': 'Cá',
'Máy đo nồng độ Oxy trong máu': 'Máy đo nồng độ Oxy trong máu',
'Đồ uống khác': 'Đồ uống khác',
'Lốp xe máy': 'Lốp xe máy',
'Vé máy bay Trong nước': 'Vé máy bay Trong nước',
'Thanh ren': 'Thanh ren',
'Kẹo trà xanh': 'Kẹo trà xanh',
'Bàn phím điện thoại': 'Bàn phím điện thoại',
'Mực máy photocopy': 'Mực máy photocopy',
'Bàn lạnh pizza': 'Bàn lạnh pizza',
'Máy rửa rau quả, thực phẩm': 'Máy rửa rau quả, thực phẩm',
'Mặt nạ ổ điện': 'Mặt nạ ổ điện',
'Bàn Billiard (Bi A)': 'Bàn Billiard (Bi A)',
'Cọ trang điểm': 'Cọ trang điểm',
'Găng tay, tất tay': 'Găng tay, tất tay',
'Tay nắm cửa': 'Tay nắm cửa',
'Phụ kiện thời trang vật nuôi': 'Phụ kiện thời trang vật nuôi',
'Thức ăn đông lạnh': 'Thức ăn đông lạnh',
'Máy đọc mã vạch': 'Máy đọc mã vạch',
'Ghế nằm (relax)': 'Ghế nằm (relax)',
'Áo len nam': 'Áo len nam',
'Chăn cho bé': 'Chăn cho bé',
'Máy tách màu gạo': 'Máy tách màu gạo',
'Ruột bút chì': 'Ruột bút chì',
'Giấy thơm quần áo': 'Giấy thơm quần áo',
'Tất y khoa': 'Tất y khoa',
'Máy bộ đàm cầm tay': 'Máy bộ đàm cầm tay',
'Đồng hồ Argon, Co2, Oxy': 'Đồng hồ Argon, Co2, Oxy',
'Kẹo chocolate': 'Kẹo chocolate',
'Bóng Tennis': 'Bóng Tennis',
'Tời nâng': 'Tời nâng',
'Thực phẩm qua sơ chế': 'Thực phẩm qua sơ chế',
'Áo cưới, váy cưới': 'Áo cưới, váy cưới',
'Máy kiểm vải': 'Máy kiểm vải',
'Tour du lịch Châu Âu': 'Tour du lịch Châu Âu',
'Kim loại và hợp kim': 'Kim loại và hợp kim',
'Khuôn cửa, khung cửa': 'Khuôn cửa, khung cửa',
'Máy tiệt trùng': 'Máy tiệt trùng',
'Máy in phun': 'Máy in phun',
'Máy lọc thông minh cho bể bơi': 'Máy lọc thông minh cho bể bơi',
'Xe Ô tô, xe máy đồ chơi': 'Xe Ô tô, xe máy đồ chơi',
'Phụ kiện phòng tắm khác': 'Phụ kiện phòng tắm khác',
'Van thủy lực': 'Van thủy lực',
'Chậu hoa, đôn hoa': 'Chậu hoa, đôn hoa',
'Bát hương': 'Bát hương',
'Dụng cụ hỗ trợ tỉa, vẽ lông mày': 'Dụng cụ hỗ trợ tỉa, vẽ lông mày',
'Áo khoác có mũ': 'Áo khoác có mũ',
'Mặt kính điện thoại': 'Mặt kính điện thoại',
'Bông tẩy trang, giấy thấm dầu': 'Bông tẩy trang, giấy thấm dầu',
'Giá treo màn hình': 'Giá treo màn hình',
'Nhà biệt thự': 'Nhà biệt thự',
'Chăm sóc cơ thể': 'Chăm sóc cơ thể',
'Jack chuyển tai nghe': 'Jack chuyển tai nghe',
'Khu nghỉ dưỡng Hòa Bình': 'Khu nghỉ dưỡng Hòa Bình',
'Muối tắm': 'Muối tắm',
'Rơ le điều khiển': 'Rơ le điều khiển',
'Cổng xếp': 'Cổng xếp',
'Thực phẩm cho bà bầu': 'Thực phẩm cho bà bầu',
'Thổ cẩm': 'Thổ cẩm',
'Ghép hình động vật': 'Ghép hình động vật',
'Máy bắn tia nước cao áp': 'Máy bắn tia nước cao áp',
'Cổng tự động': 'Cổng tự động',
'RAM(laptop)': 'RAM(laptop)',
'La bàn điện tử': 'La bàn điện tử',
'Gậy leo núi': 'Gậy leo núi',
'Rơ le bán dẫn': 'Rơ le bán dẫn',
'Dải phân cách': 'Dải phân cách',
'Nhân sâm tươi': 'Nhân sâm tươi',
'Đá ốp lát': 'Đá ốp lát',
'Động cơ gắn ngoài thuyền': 'Động cơ gắn ngoài thuyền',
'Két bán hàng': 'Két bán hàng',
'Chấn lưu': 'Chấn lưu',
'Nhôm tấm': 'Nhôm tấm',
'Máy hàn TIG': 'Máy hàn TIG',
'Phụ kiện máy hàn khác': 'Phụ kiện máy hàn khác',
'Bộ đục': 'Bộ đục',
'Phụ kiện dụng cụ nông nghiệp': 'Phụ kiện dụng cụ nông nghiệp',
'Khử mùi,Hút mùi Ôtô': 'Khử mùi,Hút mùi Ôtô',
'Rong biển khô': 'Rong biển khô',
'Máy in mã ngày': 'Máy in mã ngày',
'Váy xếp li': 'Váy xếp li',
'Vợt cầu lông': 'Vợt cầu lông',
'Robot điều khiển từ xa': 'Robot điều khiển từ xa',
'Card kỹ xảo': 'Card kỹ xảo',
'Amplifier Hi-End': 'Amplifier Hi-End',
'Bộ đồ sơ sinh': 'Bộ đồ sơ sinh',
'Cửa nhựa lõi thép': 'Cửa nhựa lõi thép',
'Lồng chụp sản phẩm': 'Lồng chụp sản phẩm',
'Phụ kiện máy cơ khí': 'Phụ kiện máy cơ khí',
'Access point (Wifi)': 'Access point (Wifi)',
'Router': 'Router',
'Nồi buffet': 'Nồi buffet',
'Cổng từ dò kim loại': 'Cổng từ dò kim loại',
'Máy làm mát không khí công nghiệp': 'Máy làm mát không khí công nghiệp',
'Thiết kế kiến trúc tổng hợp': 'Thiết kế kiến trúc tổng hợp',
'Display (màn hình Laptop)': 'Display (màn hình Laptop)',
'Túi, vỏ chống nước': 'Túi, vỏ chống nước',
'An toàn cho bé khi đi ô tô': 'An toàn cho bé khi đi ô tô',
'Trục giấy vệ sinh': 'Trục giấy vệ sinh',
'Máy phun, xịt côn trùng': 'Máy phun, xịt côn trùng',
'Pin máy tính bảng': 'Pin máy tính bảng',
'Bộ dụng cụ sửa chữa tổng hợp': 'Bộ dụng cụ sửa chữa tổng hợp',
'Tủ, lò sấy thiết bị y tế': 'Tủ, lò sấy thiết bị y tế',
'Lò xo uốn ống ( cho ống luồn dây điện )': 'Lò xo uốn ống ( cho ống luồn dây điện )',
'Tủ vải': 'Tủ vải',
'Kẹo sữa': 'Kẹo sữa',
'Hot Deal Thời trang': 'Hot Deal Thời trang',
'Bàn phím điều khiển': 'Bàn phím điều khiển',
'Mỏ lết': 'Mỏ lết',
'Trụ nhảy cao': 'Trụ nhảy cao',
'Phụ kiện quang': 'Phụ kiện quang',
'Máy khoan ổ khóa, bản lề': 'Máy khoan ổ khóa, bản lề',
'Thực phẩm hỗ trợ điều trị bệnh dạ dày': 'Thực phẩm hỗ trợ điều trị bệnh dạ dày',
'Còi xe máy': 'Còi xe máy',
'Ca, nắp nhựa': 'Ca, nắp nhựa',
'Cặp học sinh': 'Cặp học sinh',
'Thực phẩm hỗ trợ điều trị xương khớp': 'Thực phẩm hỗ trợ điều trị xương khớp',
'Buồng tắm đa năng': 'Buồng tắm đa năng',
'Bộ trộn âm (Mixer)': 'Bộ trộn âm (Mixer)',
'Hạt tiêu': 'Hạt tiêu',
'Kẹp bướm': 'Kẹp bướm',
'Bộ chụp sản phẩm': 'Bộ chụp sản phẩm',
'Đồ ăn nghiền cho bé': 'Đồ ăn nghiền cho bé',
'Xe điện': 'Xe điện',
'Ống ngắm (Viewfinder)': 'Ống ngắm (Viewfinder)',
'Quả bóng bàn': 'Quả bóng bàn',
'Túi đựng máy quay': 'Túi đựng máy quay',
'Biển chỉ': 'Biển chỉ',
'Đai massage bụng': 'Đai massage bụng',
'Hệ thống kiểm soát ra vào': 'Hệ thống kiểm soát ra vào',
'Máy giặt thảm': 'Máy giặt thảm',
'Phụ kiện xe đạp': 'Phụ kiện xe đạp',
'Cốc giấy': 'Cốc giấy',
'Cà phê giảm cân': 'Cà phê giảm cân',
'Van xả khí': 'Van xả khí',
'Phụ kiện thiết bị cầm tay': 'Phụ kiện thiết bị cầm tay',
'Bàn ghế phòng ngủ': 'Bàn ghế phòng ngủ',
'Baga xe máy': 'Baga xe máy',
'Máy hủy tài liệu': 'Máy hủy tài liệu',
'Gạch xây': 'Gạch xây',
'Phòng của bé': 'Phòng của bé',
'Kính mắt Hồng Kông nữ': 'Kính mắt Hồng Kông nữ',
'Màn (mùng) cho bé': 'Màn (mùng) cho bé',
'Sound Card': 'Sound Card',
'Trung tâm báo cháy': 'Trung tâm báo cháy',
'Máy sủi': 'Máy sủi',
'Vách chống cháy': 'Vách chống cháy',
'Máy rút màng co ( máy hút màng co )': 'Máy rút màng co ( máy hút màng co )',
'Phụ kiện Toilet': 'Phụ kiện Toilet',
'Phòng tắm Spa': 'Phòng tắm Spa',
'Bếp hầm': 'Bếp hầm',
'Xe máy điều khiển từ xa': 'Xe máy điều khiển từ xa',
'Máy nghiền dược liệu': 'Máy nghiền dược liệu',
'Nhạc cụ dân tộc': 'Nhạc cụ dân tộc',
'Các món ăn khác': 'Các món ăn khác',
'Máy ép thủy lực': 'Máy ép thủy lực',
'Giá để dụng cụ sửa chữa Ô tô': 'Giá để dụng cụ sửa chữa Ô tô',
'Thiết bị PDH Multiplexer': 'Thiết bị PDH Multiplexer',
'Công tơ điện': 'Công tơ điện',
'Khay đựng hoa quả': 'Khay đựng hoa quả',
'Màn hình LCD quảng cáo - đa dụng': 'Màn hình LCD quảng cáo - đa dụng',
'In túi giấy': 'In túi giấy',
'Khăn tắm cho bé': 'Khăn tắm cho bé',
'Bút đo nhiệt kế, Cặp nhiệt độ': 'Bút đo nhiệt kế, Cặp nhiệt độ',
'Dầu, nhớt công nghiệp': 'Dầu, nhớt công nghiệp',
'Bạc biên Ô tô': 'Bạc biên Ô tô',
'Đế (chân) nến thờ': 'Đế (chân) nến thờ',
'Bộ bình thở ( bộ bình khí o2 )': 'Bộ bình thở ( bộ bình khí o2 )',
'Buộc tóc': 'Buộc tóc',
'Bình khí nén': 'Bình khí nén',
'Xi lanh (bơm kim tiêm)': 'Xi lanh (bơm kim tiêm)',
'Phụ tùng phụ kiện tàu thuyền khác': 'Phụ tùng phụ kiện tàu thuyền khác',
'Đồ chơi chữ viết': 'Đồ chơi chữ viết',
'Máy tách xương cá': 'Máy tách xương cá',
'Công tắc cảm ứng chuyển động': 'Công tắc cảm ứng chuyển động',
'Túi, hộp mỹ phẩm': 'Túi, hộp mỹ phẩm',
'Bao cố định chấn thương': 'Bao cố định chấn thương',
'Máy rang cà phê': 'Máy rang cà phê',
'Nguồn máy tính (PSU)': 'Nguồn máy tính (PSU)',
'Kệ kính phòng tắm': 'Kệ kính phòng tắm',
'Chậu rửa khẩn cấp': 'Chậu rửa khẩn cấp',
'Phụ kiện máy đo đạc, trắc địa': 'Phụ kiện máy đo đạc, trắc địa',
'Máy bào gỗ': 'Máy bào gỗ',
'Tay máy hàn thiếc': 'Tay máy hàn thiếc',
'Dao cắt ống': 'Dao cắt ống',
'Kẹo sâm': 'Kẹo sâm',
'Áo khoác cổ lông': 'Áo khoác cổ lông',
'Dụng cụ y tế khác': 'Dụng cụ y tế khác',
'Module quang': 'Module quang',
'Quạt hơi nước': 'Quạt hơi nước',
'Quạt đèn trang trí': 'Quạt đèn trang trí',
'Phụ kiện máy phun rửa áp lực': 'Phụ kiện máy phun rửa áp lực',
'Máy dán cạnh': 'Máy dán cạnh',
'Máy chiết rót': 'Máy chiết rót',
'Vách ngăn gỗ ốp': 'Vách ngăn gỗ ốp',
'Máy nạp ắc quy': 'Máy nạp ắc quy',
'Ghế băng công cộng': 'Ghế băng công cộng',
'Công tắc đôi': 'Công tắc đôi',
'Kẹp tóc, cặp tóc trẻ em': 'Kẹp tóc, cặp tóc trẻ em',
'Súng hàn': 'Súng hàn',
'Kéo, dao cạo': 'Kéo, dao cạo',
'Thiết bị cơ khí Ôtô khác': 'Thiết bị cơ khí Ôtô khác',
'Điều hòa công nghiệp': 'Điều hòa công nghiệp',
'Phục trang Triều đình nam': 'Phục trang Triều đình nam',
'Phụ kiện máy tập chạy bộ': 'Phụ kiện máy tập chạy bộ',
'Ống dẫn công nghiệp khác': 'Ống dẫn công nghiệp khác',
'Cảm biến áp lực ( áp suất )': 'Cảm biến áp lực ( áp suất )',
'Dịch vụ sửa chữa thiết bị': 'Dịch vụ sửa chữa thiết bị',
'Máy làm lạnh nước hoa quả': 'Máy làm lạnh nước hoa quả',
'Mac Accessories': 'Mac Accessories',
'Chì kẻ viền mắt': 'Chì kẻ viền mắt',
'Chuông cửa có màn hình': 'Chuông cửa có màn hình',
'Máy bơm và hút dầu thải xe máy': 'Máy bơm và hút dầu thải xe máy',
'Nhà hơi, nhà phao': 'Nhà hơi, nhà phao',
'Dụng cụ đựng & Chế biến thực phẩm': 'Dụng cụ đựng & Chế biến thực phẩm',
'Vô Lăng Ô tô': 'Vô Lăng Ô tô',
'Chất rửa chén, bát': 'Chất rửa chén, bát',
'Bếp điện': 'Bếp điện',
'Thanh treo khăn đôi': 'Thanh treo khăn đôi',
'Vali đi học': 'Vali đi học',
'Dao cạo, bàn cạo râu': 'Dao cạo, bàn cạo râu',
'Máy khoan bàn': 'Máy khoan bàn',
'Thiết bị tạo nhiệt bo mạch': 'Thiết bị tạo nhiệt bo mạch',
'Đui đèn': 'Đui đèn',
'Thiết bị điều khiển tưới sân vườn': 'Thiết bị điều khiển tưới sân vườn',
'Ván gỗ': 'Ván gỗ',
'Phân bón, đạm, tăng trưởng': 'Phân bón, đạm, tăng trưởng',
'Thiết bị giảm cân': 'Thiết bị giảm cân',
'Tay treo hắt sáng': 'Tay treo hắt sáng',
'Khuôn hàn': 'Khuôn hàn',
'Mực xăm': 'Mực xăm',
'Máy dán thùng carton': 'Máy dán thùng carton',
'Món Tôm': 'Món Tôm',
'Thiết bị đo khí độc': 'Thiết bị đo khí độc',
'Quạt treo tường': 'Quạt treo tường',
'Bàn chụp sản phẩm': 'Bàn chụp sản phẩm',
'File tài liệu': 'File tài liệu',
'Dây mạng': 'Dây mạng',
'Đèn cây': 'Đèn cây',
'Máy xét nghiệm máu': 'Máy xét nghiệm máu',
'Đèn mổ': 'Đèn mổ',
'Máy phát điện dân dụng': 'Máy phát điện dân dụng',
'Thức ăn chăn nuôi': 'Thức ăn chăn nuôi',
'Nồi chiên đa năng': 'Nồi chiên đa năng',
'Hộp giữ nhiệt thức ăn cho bé': 'Hộp giữ nhiệt thức ăn cho bé',
'Kính mắt hàng hiệu trẻ em': 'Kính mắt hàng hiệu trẻ em',
'Bơm thủy lực': 'Bơm thủy lực',
'Dưỡng móng': 'Dưỡng móng',
'Bút đánh dấu bề mặt': 'Bút đánh dấu bề mặt',
'Thẻ cảm ứng': 'Thẻ cảm ứng',
'Bánh ngũ cốc': 'Bánh ngũ cốc',
'Máy làm sữa chua': 'Máy làm sữa chua',
'Phích cắm điện': 'Phích cắm điện',
'Cần cẩu': 'Cần cẩu',
'Máy tạo kiểu tóc': 'Máy tạo kiểu tóc',
'Bài vị thờ': 'Bài vị thờ',
'Phụ kiện kết nối': 'Phụ kiện kết nối',
'Thanh chống va đập': 'Thanh chống va đập',
'Hoa sinh nhật': 'Hoa sinh nhật',
'Máy sinh hóa': 'Máy sinh hóa',
'Thiết bị cân vành xe máy': 'Thiết bị cân vành xe máy',
'Phụ kiện thông minh': 'Phụ kiện thông minh',
'Gia vị rắc cơm': 'Gia vị rắc cơm',
'Bô, thùng rác cho bé': 'Bô, thùng rác cho bé',
'Súng dán keo': 'Súng dán keo',
'Bộ điều khiển máy móc': 'Bộ điều khiển máy móc',
'Đồng hồ đo điện trở': 'Đồng hồ đo điện trở',
'Chăn ủ cho bé': 'Chăn ủ cho bé',
'Sắt nghệ thuật': 'Sắt nghệ thuật',
'Dụng cụ chỉnh sửa móng': 'Dụng cụ chỉnh sửa móng',
'Đồ chơi': 'Đồ chơi',
'Phụ kiện hệ thống kiểm soát ra vào': 'Phụ kiện hệ thống kiểm soát ra vào',
'Mô tơ cửa': 'Mô tơ cửa',
'LED Displays - bóng đèn LED': 'LED Displays - bóng đèn LED',
'Máy photocopy cũ': 'Máy photocopy cũ',
'Đồ chơi thể thao tổng hợp': 'Đồ chơi thể thao tổng hợp',
'Bộ sập tủ chè': 'Bộ sập tủ chè',
'Máy làm sữa đậu nành': 'Máy làm sữa đậu nành',
'Sản phẩm thêu thùa': 'Sản phẩm thêu thùa',
'Dầu nhớt cho động cơ xe máy': 'Dầu nhớt cho động cơ xe máy',
'Máy biến áp': 'Máy biến áp',
'Sữa rửa mặt nam': 'Sữa rửa mặt nam',
'Máy thu hoạch khoai tây': 'Máy thu hoạch khoai tây',
'Bộ lưu điện cho cửa cuốn': 'Bộ lưu điện cho cửa cuốn',
'Áo bầu': 'Áo bầu',
'Rulo cuốn ống khí nén': 'Rulo cuốn ống khí nén',
'Xi đánh bóng Ôtô': 'Xi đánh bóng Ôtô',
'Nồi áp suất': 'Nồi áp suất',
'Gạch không nung siêu nhẹ': 'Gạch không nung siêu nhẹ',
'Cung cấp trang phục tổ chức sự kiện': 'Cung cấp trang phục tổ chức sự kiện',
'Pin thông dụng': 'Pin thông dụng',
'Hot Deal Đào tạo': 'Hot Deal Đào tạo',
'Khay mực in': 'Khay mực in',
'Máy sấy khô bát': 'Máy sấy khô bát',
'Bấm ghim, đục lỗ': 'Bấm ghim, đục lỗ',
'Hộp đựng kính': 'Hộp đựng kính',
'Máy cắt đá': 'Máy cắt đá',
'Cân chiết rót': 'Cân chiết rót',
'Tồn ngai thờ': 'Tồn ngai thờ',
'Phụ kiện khóa điện tử': 'Phụ kiện khóa điện tử',
'Đuốc hàn': 'Đuốc hàn',
'Thép hộp': 'Thép hộp',
'Dịch vụ sửa chữa điện thoại': 'Dịch vụ sửa chữa điện thoại',
'Bộ giải mã DAC': 'Bộ giải mã DAC',
'Linh kiện máy nghe nhạc': 'Linh kiện máy nghe nhạc',
'Đèn trang trí dưới nước': 'Đèn trang trí dưới nước',
'Máy gieo hạt, xới cỏ và bón phân': 'Máy gieo hạt, xới cỏ và bón phân',
'Đồ chơi hóa trang': 'Đồ chơi hóa trang',
'Uốn mi': 'Uốn mi',
'Máy hút ẩm công nghiệp': 'Máy hút ẩm công nghiệp',
'Tủ sách': 'Tủ sách',
'Thiết bị định vị GPS': 'Thiết bị định vị GPS',
'Ống đồng': 'Ống đồng',
'Cung cấp công nghệ': 'Cung cấp công nghệ',
'Dịch vụ cắt, khắc laser': 'Dịch vụ cắt, khắc laser',
'Thực phẩm bổ dưỡng dành cho trẻ em': 'Thực phẩm bổ dưỡng dành cho trẻ em',
'Bếp gas âm': 'Bếp gas âm',
'Gương trang điểm': 'Gương trang điểm',
'Lá côn Ô tô': 'Lá côn Ô tô',
'Đồ chơi môn Câu cá': 'Đồ chơi môn Câu cá',
'Nước hoa quả ngâm': 'Nước hoa quả ngâm',
'Đồ chơi môn Bóng rổ': 'Đồ chơi môn Bóng rổ',
'Chóa đèn': 'Chóa đèn',
'Cho bé sơ sinh': 'Cho bé sơ sinh',
'Cổng trượt': 'Cổng trượt',
'Tải giả điện tử DC': 'Tải giả điện tử DC',
'Máy rang hạt nông sản': 'Máy rang hạt nông sản',
'Máy cất nước': 'Máy cất nước',
'Connectors - Đầu nối': 'Connectors - Đầu nối',
'Lều chơi': 'Lều chơi',
'USB memory': 'USB memory',
'Thép cuộn': 'Thép cuộn',
'Cửa kéo': 'Cửa kéo',
'Bồn tắm góc (bồn ngâm)': 'Bồn tắm góc (bồn ngâm)',
'Tủ lạnh ô tô': 'Tủ lạnh ô tô',
'Gậy đánh Golf': 'Gậy đánh Golf',
'Cửa lùa': 'Cửa lùa',
'Chụp ảnh nghệ thuật': 'Chụp ảnh nghệ thuật',
'Tranh vải dán tường': 'Tranh vải dán tường',
'Công tắc gạt': 'Công tắc gạt',
'Thiết bị kiểm định ô tô': 'Thiết bị kiểm định ô tô',
'Nhíp gắp tụ': 'Nhíp gắp tụ',
'Van áp suất': 'Van áp suất',
'Kệ đựng đồ phòng tắm': 'Kệ đựng đồ phòng tắm',
'Máy ép nhiệt (gỗ)': 'Máy ép nhiệt (gỗ)',
'Nồi nấu cháo công nghiệp': 'Nồi nấu cháo công nghiệp',
'Quần ngố nam': 'Quần ngố nam',
'Nhau thai cừu': 'Nhau thai cừu',
'Hàng rào': 'Hàng rào',
'Phụ kiện báo, chữa cháy khác': 'Phụ kiện báo, chữa cháy khác',
'Các phụ kiện điện thoại khác': 'Các phụ kiện điện thoại khác',
'Máy cấy': 'Máy cấy',
'Tổ yến thô': 'Tổ yến thô',
'Đai ốc': 'Đai ốc',
'Khung kéo phông': 'Khung kéo phông',
'Máy đùn xúc xích': 'Máy đùn xúc xích',
'Áo váy bầu': 'Áo váy bầu',
'Bộ phụ kiện điện thoại': 'Bộ phụ kiện điện thoại',
'Đèn sạc': 'Đèn sạc',
'Phụ kiện đèn chiếu sáng': 'Phụ kiện đèn chiếu sáng',
'Bàn ghế phòng thí nghiệm': 'Bàn ghế phòng thí nghiệm',
'Máy cân bằng bánh xe Ôtô': 'Máy cân bằng bánh xe Ôtô',
'Kính ốp': 'Kính ốp',
'Kim xăm': 'Kim xăm',
'Rơ le bảo vệ kết hợp': 'Rơ le bảo vệ kết hợp',
'Fibre Media Converter': 'Fibre Media Converter',
'Chắn bùn xe máy': 'Chắn bùn xe máy',
'Sản phẩm từ tổ yến': 'Sản phẩm từ tổ yến',
'In bao bì, nhãn mác': 'In bao bì, nhãn mác',
'Quạt thông gió dân dụng': 'Quạt thông gió dân dụng',
'Đồ độ Ô tô': 'Đồ độ Ô tô',
'Phòng học bộ môn': 'Phòng học bộ môn',
'Kẹp đa năng': 'Kẹp đa năng',
'Bánh chocolate': 'Bánh chocolate',
'Thiết bị giảm chấn': 'Thiết bị giảm chấn',
'Tivi OLED': 'Tivi OLED',
'Phụ kiện máy tính bảng (Tablet Accessories)': 'Phụ kiện máy tính bảng (Tablet Accessories)',
'Dịch vụ gia công, chế tạo': 'Dịch vụ gia công, chế tạo',
'Máy cán bột ( nghiền bột , xay bột )': 'Máy cán bột ( nghiền bột , xay bột )',
'Máy làm khăn sạch': 'Máy làm khăn sạch',
'Nhổ ghim': 'Nhổ ghim',
'Linh kiện, chân sạc, cáp trong điện thoại': 'Linh kiện, chân sạc, cáp trong điện thoại',
'Dụng cụ bổ trợ may': 'Dụng cụ bổ trợ may',
'SP chăm sóc sức khỏe, sắc đẹp khác': 'SP chăm sóc sức khỏe, sắc đẹp khác',
'Thước kẻ': 'Thước kẻ',
'Gọng kính thời trang': 'Gọng kính thời trang',
'Máy in 3D': 'Máy in 3D',
'Máy xay cà phê': 'Máy xay cà phê',
'Xe đẩy hành lý': 'Xe đẩy hành lý',
'Tripod Head': 'Tripod Head',
'Thước đo khe hở': 'Thước đo khe hở',
'Nến điện tử': 'Nến điện tử',
'Van một chiều': 'Van một chiều',
'Thùng đựng gạo': 'Thùng đựng gạo',
'Thanh ốp cột, góc tường': 'Thanh ốp cột, góc tường',
'Cảm biến từ': 'Cảm biến từ',
'Máy đóng trà túi lọc': 'Máy đóng trà túi lọc',
'Compa': 'Compa',
'Váy sơ sinh': 'Váy sơ sinh',
'Máy rửa chén, bát công nghiệp': 'Máy rửa chén, bát công nghiệp',
'Phụ kiện sàn gỗ': 'Phụ kiện sàn gỗ',
'Hoa chúc mừng': 'Hoa chúc mừng',
'Cho thuê xe du lịch': 'Cho thuê xe du lịch',
'Thuốc giảm cân': 'Thuốc giảm cân',
'Máy đo thính lực': 'Máy đo thính lực',
'Bộ trả nước về bể bơi': 'Bộ trả nước về bể bơi',
'Thiết kế phòng khách': 'Thiết kế phòng khách',
'Máy sốc tim': 'Máy sốc tim',
'Váy quây': 'Váy quây',
'Thép hình': 'Thép hình',
'Cáp thép': 'Cáp thép',
'Đầu gắn mũi khoan': 'Đầu gắn mũi khoan',
'Nước súc miệng': 'Nước súc miệng',
'Đầu đĩa than': 'Đầu đĩa than',
'Máy làm vỏ ốc quế': 'Máy làm vỏ ốc quế',
'Tóc giả': 'Tóc giả',
'Đĩa mài': 'Đĩa mài',
'Bạt phủ Ô tô': 'Bạt phủ Ô tô',
'Vòi hoa sen, vòi nước': 'Vòi hoa sen, vòi nước',
'Băng mực cho máy in Kim': 'Băng mực cho máy in Kim',
'Phao, Áo phao': 'Phao, Áo phao',
'Máy ép nhiệt, cán màng': 'Máy ép nhiệt, cán màng',
'Chó cảnh': 'Chó cảnh',
'Panel PC - máy tính Panel': 'Panel PC - máy tính Panel',
'Sản phẩm khử mùi cho nam': 'Sản phẩm khử mùi cho nam',
'Rèm cửa khác': 'Rèm cửa khác',
'Cung cấp trang thiết bị tổ chức sự kiện': 'Cung cấp trang thiết bị tổ chức sự kiện',
'Bình phong tre': 'Bình phong tre',
'Giá, tủ, kệ đựng đĩa CD': 'Giá, tủ, kệ đựng đĩa CD',
'Hộp tỳ tay trên Ô tô': 'Hộp tỳ tay trên Ô tô',
'Bộ đồ ăn cho bé': 'Bộ đồ ăn cho bé',
'Ghép hình công trình nổi tiếng': 'Ghép hình công trình nổi tiếng',
'Vòi xịt vệ sinh phòng tắm': 'Vòi xịt vệ sinh phòng tắm',
'Trụ chữa cháy ( trụ cứu hỏa )': 'Trụ chữa cháy ( trụ cứu hỏa )',
'Bột đậu đỏ': 'Bột đậu đỏ',
'Loa phóng thanh': 'Loa phóng thanh',
'Máy tạo hạt phân bón': 'Máy tạo hạt phân bón',
'Micro ghi âm camera': 'Micro ghi âm camera',
'Máy đo đường huyết': 'Máy đo đường huyết',
'Công tắc hẹn giờ ( công tắc đồng hồ )': 'Công tắc hẹn giờ ( công tắc đồng hồ )',
'Gạch granite': 'Gạch granite',
'Các phụ tùng xe đạp khác': 'Các phụ tùng xe đạp khác',
'Cừ thép ( thép cọc cừ )': 'Cừ thép ( thép cọc cừ )',
'Bơm thùng phuy': 'Bơm thùng phuy',
'Bộ điều khiển van khí nén': 'Bộ điều khiển van khí nén',
'Mi giả': 'Mi giả',
'Công tắc ba': 'Công tắc ba',
'Lưỡi câu': 'Lưỡi câu',
'Máy ấp trứng gia cầm': 'Máy ấp trứng gia cầm',
'Loa ôtô': 'Loa ôtô',
'Các sản phẩm cơ khí khác': 'Các sản phẩm cơ khí khác',
'Máy kiểm kho': 'Máy kiểm kho',
'Chụp khí': 'Chụp khí',
'Bông, băng, gạc': 'Bông, băng, gạc',
'Súng xịt hơi ( súng xịt khí )': 'Súng xịt hơi ( súng xịt khí )',
'Máy ghi âm điện thoại': 'Máy ghi âm điện thoại',
'Điều khiển máy ảnh': 'Điều khiển máy ảnh',
'Đai giữ bụng bầu': 'Đai giữ bụng bầu',
'Nguyên liệu, hương liệu mỹ phẩm': 'Nguyên liệu, hương liệu mỹ phẩm',
'Thép cây ( thép thanh )': 'Thép cây ( thép thanh )',
'Tất phun': 'Tất phun',
'Bóng rổ': 'Bóng rổ',
'Bia': 'Bia',
'Bánh pía': 'Bánh pía'
}
# Iterate over the substrings and replacement labels, and update the 'Label' values
for substring, replacement_label in substring_replacements.items():
    df2.loc[df2['Product Name'].str.contains(substring), 'Label'] = replacement_label

df2.to_csv('df3.csv', index=False)

print("Done")
